diccionario_semantico = {
    "Vivienda": [
        "renta",
        "alquiler",
        "hipoteca",
        "luz",
        "electricidad",
        "recibo de luz",
        "agua",
        "recibo de agua",
        "gas",
        "gas lp",
        "gas natural",
        "internet",
        "wifi",
        "cable",
        "telefono fijo",
        "mantenimiento",
        "mantenimiento de casa",
        "mantenimiento del departamento",
        "cuota de condominio",
        "predial",
        "reparacion de casa",
        "plomeria",
        "electricista",
        "pintura de la casa",
        "muebles necesarios",
        "electrodomesticos del hogar"
    ],

    "Alimentación": [
        "despensa",
        "super",
        "supermercado",
        "mandado",
        "comida",
        "alimentos",
        "mercado",
        "abarrotes",
        "frutas",
        "verduras",
        "carne",
        "pollo",
        "pescado",
        "leche",
        "huevos",
        "pan",
        "tortillas",
        "cereal",
        "arroz",
        "frijoles",
        "agua embotellada",
        "refresco",
        "snacks",
        "comida para la casa",
        "ingredientes",
        "compras del super"
    ],

    "Transporte": [
        "pasaje",
        "transporte",
        "camion",
        "autobus",
        "metro",
        "metrobus",
        "taxi",
        "uber",
        "didi",
        "gasolina",
        "combustible",
        "llenar el tanque",
        "carga de gasolina",
        "casetas",
        "peaje",
        "estacionamiento",
        "parking",
        "pension del coche",
        "mantenimiento del coche",
        "servicio del coche",
        "afinacion",
        "cambio de aceite",
        "llantas",
        "reparacion del coche",
        "verificacion",
        "tenencia",
        "seguro del coche"
    ],

    "Salud": [
        "medicinas",
        "medicamentos",
        "farmacia",
        "consulta",
        "doctor",
        "medico",
        "consulta medica",
        "especialista",
        "dentista",
        "consulta dental",
        "psicologo",
        "terapia",
        "terapia fisica",
        "laboratorio",
        "analisis clinicos",
        "estudios medicos",
        "rayos x",
        "ultrasonido",
        "resonancia",
        "hospital",
        "urgencias",
        "cirugia",
        "lentes",
        "optometrista",
        "seguro medico",
        "seguro de gastos medicos",
        "vacunas",
        "vitaminas",
        "tratamiento"
    ],

    "Educación": [
        "colegiatura",
        "escuela",
        "mensualidad de la escuela",
        "inscripcion",
        "reinscripcion",
        "universidad",
        "curso",
        "clases",
        "diplomado",
        "certificacion",
        "capacitacion",
        "maestria",
        "posgrado",
        "libros",
        "libros escolares",
        "utiles",
        "utiles escolares",
        "cuadernos",
        "mochila",
        "uniforme",
        "material escolar",
        "copias",
        "impresiones",
        "clases de ingles",
        "clases particulares",
        "plataforma educativa"
    ],

    "Entretenimiento y ocio": [
        "cine",
        "pelicula",
        "boletos de cine",
        "concierto",
        "boletos de concierto",
        "festival",
        "bar",
        "antro",
        "salida",
        "salida con amigos",
        "fiesta",
        "restaurante",
        "cena",
        "comida fuera",
        "desayuno fuera",
        "cafeteria",
        "cafe",
        "boliche",
        "billar",
        "karaoke",
        "videojuegos",
        "juegos",
        "parque de diversiones",
        "museo",
        "evento",
        "espectaculo",
        "teatro",
        "ocio"
    ],

    "Suscripciones digitales": [
        "netflix",
        "spotify",
        "disney plus",
        "disney+",
        "max",
        "hbo max",
        "youtube premium",
        "amazon prime",
        "prime video",
        "apple music",
        "apple tv",
        "icloud",
        "google one",
        "microsoft 365",
        "xbox game pass",
        "playstation plus",
        "nintendo switch online",
        "dropbox",
        "canva pro",
        "adobe",
        "adobe creative cloud",
        "chatgpt plus",
        "suscripcion",
        "suscripcion mensual",
        "streaming",
        "plataforma digital",
        "membresia digital"
    ],

    "Compras personales": [
        "ropa",
        "camisa",
        "playera",
        "pantalon",
        "vestido",
        "chamarra",
        "sudadera",
        "tenis",
        "zapatos",
        "botas",
        "sandalias",
        "maquillaje",
        "cosmeticos",
        "perfume",
        "cremas",
        "skincare",
        "bolsa",
        "mochila personal",
        "cartera",
        "reloj",
        "joyeria",
        "accesorios",
        "audifonos",
        "celular",
        "telefono",
        "tablet",
        "computadora personal",
        "electronicos",
        "decoracion",
        "regalo"
    ],

    "Viajes y vacaciones": [
        "viaje",
        "vacaciones",
        "vuelo",
        "avion",
        "boletos de avion",
        "hotel",
        "hospedaje",
        "airbnb",
        "hostal",
        "resort",
        "tour",
        "excursion",
        "paquete de viaje",
        "renta de auto",
        "taxi del aeropuerto",
        "transporte al aeropuerto",
        "maleta",
        "equipaje",
        "seguro de viaje",
        "comida de viaje",
        "restaurante de vacaciones",
        "actividades de viaje",
        "entrada a atraccion",
        "vacaciones familiares"
    ],

    "Otros": [
        "donacion",
        "regalo para alguien",
        "mascota",
        "veterinario",
        "alimento para mascota",
        "tramite",
        "documento",
        "comision bancaria",
        "cargo bancario",
        "multa",
        "impuesto",
        "pago al sat",
        "servicio profesional",
        "abogado",
        "contador",
        "reparacion inesperada",
        "gasto imprevisto",
        "otro gasto"
    ]
}