diccionario_tipo_movimiento = {
    "Ingreso": [
        "salario",
        "sueldo",
        "nomina",
        "quincena",
        "pago de trabajo",
        "honorarios",
        "freelance",
        "trabajo freelance",
        "comision",
        "comisiones",
        "bono",
        "aguinaldo",
        "utilidades",
        "pension",
        "jubilacion",
        "renta recibida",
        "transferencia recibida",
        "venta",
        "ingreso extra",
        "rendimientos",
        "dividendos",
        "intereses ganados"
    ],

    "Pago de deuda": [
        "pago de tarjeta",
        "pago tarjeta",
        "pago tdc",
        "pago tc",
        "abono tarjeta",
        "pago de credito",
        "pago credito",
        "mensualidad del credito",
        "pago de prestamo",
        "abono a prestamo",
        "pago hipotecario",
        "pago de hipoteca",
        "pago automotriz",
        "mensualidad del coche",
        "liquidacion de deuda"
    ],

    "Ahorro e inversión": [
        "ahorro",
        "guardar dinero",
        "fondo de emergencia",
        "cuenta de ahorro",
        "apartado de ahorro",
        "cetes",
        "cetes directo",
        "inversion",
        "invertir",
        "fondo de inversion",
        "acciones",
        "etf",
        "afore",
        "aportacion afore",
        "pagare",
        "bonos",
        "fondo indexado",
        "casa de bolsa",
        "gbm",
        "actinver"
    ]
}
