"""Diccionarios semánticos ampliados para la generación sintética de FinanceAI.

Diseño:
    etiqueta -> concepto semántico -> expresiones naturales

Los conceptos son metadatos del generador y NO deben utilizarse como features
del modelo. Las expresiones buscan imitar la manera en que una persona
describiría manualmente un movimiento, no el descriptor de un estado bancario.
"""


DICCIONARIO_TIPO_MOVIMIENTO = {
    "Ingreso": {
        "salario_nomina": [
            "salario",
            "sueldo",
            "nómina",
            "me cayó la nómina",
            "pago de la quincena",
            "me depositaron la quincena",
            "pago del trabajo",
            "depósito de mi sueldo",
            "sueldo de este mes",
            "me pagaron del trabajo",
        ],
        "honorarios_freelance": [
            "honorarios",
            "pago de honorarios",
            "pago de un proyecto",
            "me pagaron un proyecto",
            "trabajo freelance",
            "pago freelance",
            "me pagó un cliente",
            "cobré un trabajo",
            "ingreso por un proyecto",
            "pago por servicios profesionales",
        ],
        "comisiones_bonos": [
            "comisión por ventas",
            "comisiones del mes",
            "bono del trabajo",
            "me dieron un bono",
            "bono de productividad",
            "bono por resultados",
            "pago de comisiones",
            "incentivo del trabajo",
        ],
        "prestaciones_laborales": [
            "aguinaldo",
            "me depositaron el aguinaldo",
            "utilidades",
            "pago de utilidades",
            "prima vacacional",
            "fondo de ahorro de la empresa",
            "liquidación del trabajo",
            "indemnización laboral",
        ],
        "pension_jubilacion": [
            "pensión",
            "pago de pensión",
            "depósito de mi pensión",
            "jubilación",
            "pago de jubilación",
            "me depositaron la pensión",
        ],
        "rentas_recibidas": [
            "renta que me pagaron",
            "renta recibida",
            "me pagaron la renta",
            "ingreso de la renta",
            "pago del inquilino",
            "depósito del inquilino",
        ],
        "ventas": [
            "vendí unas cosas",
            "venta de un artículo",
            "me pagaron una venta",
            "dinero de una venta",
            "venta por internet",
            "vendí mi celular",
            "vendí un mueble",
            "cobro de mercancía vendida",
        ],
        "ingresos_extraordinarios": [
            "ingreso extra",
            "dinero extra",
            "me entró un dinero extra",
            "apoyo económico recibido",
            "dinero que me mandaron",
            "remesa que recibí",
            "me mandó dinero mi familia",
            "herencia recibida",
        ],
        "rendimientos_recibidos": [
            "rendimientos de inversión",
            "me pagaron rendimientos",
            "dividendos",
            "pago de dividendos",
            "intereses ganados",
            "ganancia de una inversión",
            "rendimiento de CETES",
        ],
    },

    "Pago de deuda": {
        "tarjeta_credito": [
            "pago de tarjeta",
            "pagué la tarjeta",
            "pago de mi tarjeta de crédito",
            "abono a la tarjeta",
            "aboné a la tarjeta",
            "pago de la TDC",
            "pagué el saldo de la tarjeta",
            "pago mínimo de la tarjeta",
            "di el mínimo de la tarjeta",
            "liquidé la tarjeta",
            "pagué todo lo de la tarjeta",
        ],
        "prestamo_personal": [
            "pago del préstamo",
            "pagué el préstamo",
            "abono al préstamo",
            "mensualidad del préstamo",
            "pago de préstamo personal",
            "aboné a mi préstamo",
            "pago del crédito personal",
            "mensualidad del crédito personal",
        ],
        "hipoteca": [
            "pago de hipoteca",
            "pagué la hipoteca",
            "mensualidad de la hipoteca",
            "abono a la hipoteca",
            "pago del crédito hipotecario",
            "mensualidad de la casa",
            "abono al crédito de la casa",
        ],
        "credito_automotriz": [
            "pago del crédito del coche",
            "mensualidad del coche",
            "pago del carro",
            "mensualidad del carro",
            "abono al crédito automotriz",
            "pago del crédito automotriz",
            "pagué la mensualidad del auto",
        ],
        "credito_departamental": [
            "pago de la tienda departamental",
            "abono a la tienda",
            "pago del crédito de la tienda",
            "mensualidad de la tienda",
            "pagué mi crédito departamental",
            "abono de la compra a crédito",
        ],
        "otras_deudas": [
            "pago de una deuda",
            "aboné a una deuda",
            "liquidación de deuda",
            "liquidé una deuda",
            "pago pendiente que debía",
            "abono de deuda",
            "pago de financiamiento",
            "mensualidad del financiamiento",
        ],
    },

    "Ahorro e inversión": {
        "ahorro_general": [
            "ahorro",
            "guardé dinero",
            "aparté dinero para ahorrar",
            "pasé dinero a mis ahorros",
            "dinero para ahorrar",
            "ahorro del mes",
            "aparté una parte de la quincena",
            "guardé parte de mi sueldo",
            "transferí a mi cuenta de ahorro",
        ],
        "fondo_emergencia": [
            "fondo de emergencia",
            "dinero para emergencias",
            "aparté para emergencias",
            "ahorro para imprevistos",
            "guardé dinero para cualquier emergencia",
            "aportación al fondo de emergencia",
        ],
        "cetes_bonos": [
            "CETES",
            "compré CETES",
            "invertí en CETES",
            "aportación a CETES",
            "CETES Directo",
            "bonos",
            "compré bonos",
            "invertí en bonos del gobierno",
        ],
        "fondos_inversion": [
            "fondo de inversión",
            "aportación al fondo de inversión",
            "metí dinero al fondo de inversión",
            "invertí en un fondo",
            "fondo indexado",
            "aportación al fondo indexado",
            "puse dinero en mi inversión",
        ],
        "bolsa": [
            "compré acciones",
            "invertí en acciones",
            "compré un ETF",
            "invertí en ETFs",
            "aportación a mi casa de bolsa",
            "metí dinero a GBM",
            "transferí a mi cuenta de inversión",
            "compré participaciones de un fondo",
        ],
        "retiro": [
            "aportación al AFORE",
            "aportación voluntaria al AFORE",
            "ahorro para el retiro",
            "aporté para mi retiro",
            "plan personal de retiro",
            "aportación al plan de retiro",
        ],
        "otros_instrumentos": [
            "pagaré bancario",
            "invertí en un pagaré",
            "depósito a plazo",
            "inversión a plazo fijo",
            "metí dinero a Actinver",
            "aportación a mi inversión",
        ],
    },
}


DICCIONARIO_CATEGORIA = {
    "Vivienda": {
        "renta": [
            "renta",
            "pagué la renta",
            "renta del departamento",
            "renta de la casa",
            "alquiler",
            "pago del alquiler",
            "mensualidad del departamento",
            "pago de donde vivo",
        ],
        "electricidad": [
            "luz",
            "recibo de luz",
            "pagué la luz",
            "pago de electricidad",
            "recibo de la CFE",
            "me tocó pagar la luz",
            "servicio de electricidad de la casa",
        ],
        "agua": [
            "agua",
            "recibo de agua",
            "pagué el agua",
            "servicio de agua",
            "pago del agua de la casa",
            "recibo del agua del mes",
        ],
        "gas_domestico": [
            "gas de la casa",
            "gas LP",
            "gas natural de la casa",
            "llené el tanque de gas",
            "pedí el gas",
            "recibo de gas",
            "pagué el gas de la casa",
        ],
        "internet_telecom": [
            "internet de la casa",
            "pagué el internet",
            "recibo del wifi",
            "servicio de internet",
            "teléfono fijo",
            "internet y teléfono de la casa",
            "servicio de cable de la casa",
        ],
        "mantenimiento_hogar": [
            "mantenimiento de la casa",
            "mantenimiento del departamento",
            "cuota del condominio",
            "cuota de mantenimiento",
            "arreglo de la casa",
            "reparación de una fuga",
            "vino el plomero",
            "pagué al electricista",
            "pintura para la casa",
            "reparación del techo",
            "arreglo de la instalación eléctrica",
        ],
        "equipamiento_hogar": [
            "mueble para la casa",
            "compré un refrigerador",
            "electrodoméstico para la casa",
            "cambié la lavadora",
            "compré un comedor",
            "compré una estufa",
            "cosas necesarias para la casa",
        ],
        "impuestos_vivienda": [
            "predial",
            "pago del predial",
            "impuesto de la casa",
        ],
    },

    "Alimentación": {
        "despensa": [
            "despensa",
            "hice la despensa",
            "compré la despensa",
            "mandado",
            "fui por el mandado",
            "compras del súper",
            "fui al súper",
            "supermercado",
            "comida para la casa",
            "compré comida para la semana",
            "despensa de la semana",
            "despensa de la quincena",
        ],
        "abarrotes": [
            "abarrotes",
            "compré abarrotes",
            "arroz y frijoles",
            "pan y tortillas",
            "leche y huevos",
            "cereal y leche",
            "cosas para cocinar",
            "ingredientes para la comida",
            "aceite y básicos de cocina",
        ],
        "frutas_verduras": [
            "frutas y verduras",
            "compré fruta",
            "compré verduras",
            "fui al mercado por fruta",
            "verdura para la semana",
            "fruta para la casa",
        ],
        "carnes_proteinas": [
            "carne",
            "compré carne",
            "pollo",
            "compré pollo",
            "pescado",
            "compré pescado",
            "carne para la semana",
        ],
        "bebidas_snacks_casa": [
            "agua embotellada",
            "refrescos para la casa",
            "botanas para la casa",
            "snacks del súper",
            "jugos y agua",
        ],
    },

    "Transporte": {
        "transporte_publico": [
            "pasaje",
            "camión",
            "autobús",
            "metro",
            "metrobús",
            "transporte para ir al trabajo",
            "pasaje de la semana",
            "camión para la escuela",
            "tarjeta del metro",
            "recargué mi tarjeta de transporte",
        ],
        "movilidad_app_taxi": [
            "Uber",
            "pedí un Uber",
            "Uber para ir al trabajo",
            "Uber de regreso a casa",
            "DiDi",
            "pedí un DiDi",
            "DiDi para regresar a casa",
            "taxi",
            "tomé un taxi",
            "taxi para ir al trabajo",
        ],
        "combustible": [
            "gasolina",
            "cargué gasolina",
            "fui por gasolina",
            "llené el tanque",
            "gas para el carro",
            "gasolina del coche",
            "le puse gasolina al carro",
            "combustible para el coche",
        ],
        "peajes_estacionamiento": [
            "casetas",
            "pagué casetas",
            "peaje",
            "estacionamiento",
            "pagué el estacionamiento",
            "parquímetro",
            "pensión del coche",
        ],
        "mantenimiento_vehiculo": [
            "servicio del coche",
            "mantenimiento del carro",
            "afinación",
            "cambio de aceite",
            "cambié las llantas",
            "llantas nuevas",
            "reparación del coche",
            "arreglo del carro",
            "verificación",
            "pagué la verificación",
            "tenencia del coche",
        ],
        "seguro_auto": [
            "seguro del coche",
            "seguro del carro",
            "póliza del auto",
            "pagué el seguro del auto",
        ],
    },

    "Salud": {
        "farmacia": [
            "medicinas",
            "medicamentos",
            "fui a la farmacia",
            "compré mis medicinas",
            "medicamento para el tratamiento",
            "compré unas pastillas",
            "vitaminas",
        ],
        "consulta_medica": [
            "consulta médica",
            "fui al doctor",
            "consulta con el médico",
            "cita con el doctor",
            "consulta con especialista",
            "fui con el especialista",
            "revisión médica",
        ],
        "salud_dental": [
            "dentista",
            "consulta dental",
            "fui al dentista",
            "limpieza dental",
            "tratamiento dental",
            "arreglo de una muela",
        ],
        "salud_mental_rehabilitacion": [
            "psicólogo",
            "terapia",
            "sesión de terapia",
            "terapia psicológica",
            "terapia física",
            "fisioterapia",
            "sesión de rehabilitación",
        ],
        "estudios_medicos": [
            "laboratorio",
            "análisis clínicos",
            "estudios médicos",
            "análisis de sangre",
            "rayos X",
            "ultrasonido",
            "resonancia",
            "me hice unos estudios",
        ],
        "hospital_emergencia": [
            "hospital",
            "urgencias",
            "fui a urgencias",
            "hospitalización",
            "cirugía",
            "pago del hospital",
            "atención de emergencia",
        ],
        "vision": [
            "lentes",
            "lentes nuevos",
            "examen de la vista",
            "optometrista",
        ],
        "seguro_medico": [
            "seguro médico",
            "seguro de gastos médicos",
            "póliza de gastos médicos",
            "pagué mi seguro médico",
        ],
    },

    "Educación": {
        "colegiaturas_inscripciones": [
            "colegiatura",
            "pagué la colegiatura",
            "mensualidad de la escuela",
            "inscripción",
            "reinscripción",
            "pago de la universidad",
            "mensualidad de la universidad",
            "colegiatura de mis hijos",
        ],
        "cursos_formacion": [
            "curso",
            "pagué un curso",
            "clases de inglés",
            "clases particulares",
            "diplomado",
            "certificación",
            "curso para certificarme",
            "capacitación",
            "taller de capacitación",
            "clase en línea",
        ],
        "posgrado": [
            "maestría",
            "mensualidad de la maestría",
            "posgrado",
            "pago del posgrado",
        ],
        "libros_material": [
            "libros escolares",
            "libros para la escuela",
            "útiles escolares",
            "compré cuadernos",
            "material escolar",
            "copias para la escuela",
            "impresiones de la universidad",
            "mochila para la escuela",
            "uniforme escolar",
        ],
        "plataformas_educativas": [
            "plataforma educativa",
            "suscripción del curso en línea",
            "plataforma para estudiar",
            "software para la escuela",
        ],
    },

    "Entretenimiento y ocio": {
        "cine_teatro_cultura": [
            "cine",
            "fui al cine",
            "boletos para el cine",
            "película con amigos",
            "teatro",
            "boletos para el teatro",
            "museo",
            "evento cultural",
        ],
        "conciertos_eventos": [
            "concierto",
            "boletos para un concierto",
            "festival",
            "entrada al festival",
            "espectáculo",
            "boletos para un evento",
        ],
        "salidas_sociales": [
            "salida con amigos",
            "salí con mis amigos",
            "bar con amigos",
            "fuimos a un antro",
            "fiesta",
            "una salida el fin de semana",
            "copas con amigos",
        ],
        "restaurantes_cafe": [
            "restaurante",
            "salí a cenar",
            "comida fuera",
            "desayuno fuera",
            "cena con amigos",
            "fui por un café",
            "cafetería",
            "comí fuera de casa",
            "pedí comida para cenar",
        ],
        "juegos_hobbies": [
            "videojuego",
            "compré un juego",
            "boliche",
            "billar",
            "karaoke",
            "parque de diversiones",
            "actividad de ocio",
            "hobby",
        ],
    },

    "Suscripciones digitales": {
        "video_streaming": [
            "Netflix",
            "mensualidad de Netflix",
            "Disney+",
            "pago de Disney Plus",
            "Max",
            "Prime Video",
            "Apple TV",
            "suscripción de streaming",
        ],
        "musica": [
            "Spotify",
            "Spotify Premium",
            "Apple Music",
            "YouTube Premium",
            "suscripción de música",
        ],
        "nube_productividad": [
            "iCloud",
            "Google One",
            "Dropbox",
            "Microsoft 365",
            "Canva Pro",
            "Adobe Creative Cloud",
            "ChatGPT Plus",
            "almacenamiento en la nube",
            "suscripción de software",
        ],
        "gaming": [
            "Xbox Game Pass",
            "PlayStation Plus",
            "Nintendo Switch Online",
            "suscripción de videojuegos",
        ],
        "genericas": [
            "suscripción mensual",
            "membresía digital",
            "plataforma digital",
            "pago de una app",
            "aplicación premium",
        ],
    },

    "Compras personales": {
        "ropa": [
            "compré ropa",
            "una playera",
            "camisa nueva",
            "pantalón nuevo",
            "compré un vestido",
            "una chamarra",
            "compré una sudadera",
            "ropa para mí",
        ],
        "calzado": [
            "compré tenis",
            "zapatos nuevos",
            "unas botas",
            "compré sandalias",
            "calzado nuevo",
        ],
        "belleza_cuidado": [
            "maquillaje",
            "compré maquillaje",
            "cosméticos",
            "perfume",
            "cremas",
            "productos de skincare",
            "cosas para cuidado personal",
        ],
        "accesorios": [
            "bolsa nueva",
            "cartera",
            "reloj",
            "joyería",
            "accesorios",
            "mochila para mí",
        ],
        "electronica_personal": [
            "audífonos",
            "compré unos audífonos",
            "celular nuevo",
            "compré un teléfono",
            "tablet",
            "computadora personal",
            "accesorio para el celular",
            "electrónicos para mí",
        ],
        "decoracion_caprichos": [
            "decoración",
            "compré algo para decorar",
            "un gusto que me di",
            "compra por gusto",
            "algo que vi y me gustó",
        ],
        "regalos": [
            "compré un regalo",
            "regalo de cumpleaños",
            "detalle para alguien",
        ],
    },

    "Viajes y vacaciones": {
        "vuelos_transporte": [
            "boletos de avión",
            "compré un vuelo",
            "vuelo para las vacaciones",
            "avión del viaje",
            "taxi del aeropuerto",
            "transporte al aeropuerto",
            "renta de auto para el viaje",
            "traslado durante el viaje",
        ],
        "hospedaje": [
            "hotel",
            "reservé el hotel",
            "hospedaje",
            "Airbnb",
            "reservé un Airbnb",
            "hostal",
            "resort",
            "alojamiento de las vacaciones",
        ],
        "paquetes_tours": [
            "paquete de viaje",
            "tour",
            "excursión",
            "actividad del viaje",
            "entrada a una atracción del viaje",
            "tour de las vacaciones",
        ],
        "gastos_en_destino": [
            "comida durante el viaje",
            "restaurante de las vacaciones",
            "comimos durante el viaje",
            "gastos de las vacaciones",
            "souvenir del viaje",
        ],
        "equipaje_seguro": [
            "maleta para el viaje",
            "equipaje",
            "pagué equipaje extra",
            "seguro de viaje",
            "póliza para el viaje",
        ],
        "viaje_general": [
            "viaje",
            "vacaciones",
            "vacaciones familiares",
            "viaje de fin de semana",
            "escapada de vacaciones",
        ],
    },

    "Otros": {
        "mascotas": [
            "veterinario",
            "llevé a mi perro al veterinario",
            "consulta del veterinario",
            "alimento para mi mascota",
            "croquetas",
            "medicina para mi mascota",
            "cosas para mi mascota",
        ],
        "donaciones_apoyo": [
            "donación",
            "hice una donación",
            "apoyo a un familiar",
            "le di dinero a un familiar",
            "ayuda económica a mi familia",
            "cooperación",
        ],
        "tramites_documentos": [
            "trámite",
            "pagué un trámite",
            "documentos",
            "saqué un documento",
            "renovación de documentos",
            "pago de una licencia",
        ],
        "cargos_bancarios": [
            "comisión bancaria",
            "me cobraron comisión",
            "cargo del banco",
            "cuota anual del banco",
            "comisión por manejo de cuenta",
        ],
        "impuestos_multas": [
            "impuesto",
            "pago de impuestos",
            "pago al SAT",
            "multa",
            "pagué una multa",
            "recargo de impuestos",
        ],
        "servicios_profesionales": [
            "abogado",
            "pagué al abogado",
            "contador",
            "pagué al contador",
            "servicio profesional",
            "asesoría profesional",
        ],
        "imprevistos": [
            "gasto imprevisto",
            "un gasto que no esperaba",
            "reparación inesperada",
            "tuve que pagar algo de emergencia",
            "gasto inesperado",
        ],
    },
}


GRUPO_POR_CATEGORIA = {
    "Vivienda": "Esencial",
    "Alimentación": "Esencial",
    "Transporte": "Esencial",
    "Salud": "Esencial",
    "Educación": "Esencial",
    "Entretenimiento y ocio": "Discrecional",
    "Suscripciones digitales": "Discrecional",
    "Compras personales": "Discrecional",
    "Viajes y vacaciones": "Discrecional",
    "Otros": None,
}


# Estas reglas tienen prioridad sobre coincidencias de palabras aisladas.
REGLAS_AMBIGUEDAD = [
    {
        "caso": "hipoteca",
        "regla": "Un pago o abono de hipoteca es Pago de deuda, no Consumo/Vivienda.",
    },
    {
        "caso": "credito_automotriz",
        "regla": "La mensualidad o abono del financiamiento del auto es Pago de deuda; gasolina, mantenimiento y seguro son Consumo/Transporte.",
    },
    {
        "caso": "tarjeta_credito",
        "regla": "Una compra con tarjeta de crédito conserva su categoría de Consumo y agrega Pago de deuda mediante la regla de forma de pago; no se deduce solo del texto.",
    },
    {
        "caso": "renta",
        "regla": "Pagar renta es Consumo/Vivienda; recibir renta de un inquilino es Ingreso.",
    },
    {
        "caso": "comision",
        "regla": "Comisión por ventas es Ingreso; comisión bancaria es Consumo/Otros.",
    },
    {
        "caso": "rendimientos",
        "regla": "Una aportación a inversión es Ahorro e inversión; rendimientos ya recibidos son Ingreso.",
    },
    {
        "caso": "restaurante",
        "regla": "Restaurante habitual o salida social se clasifica como Entretenimiento y ocio; si el texto indica que ocurrió durante vacaciones, Viajes y vacaciones.",
    },
    {
        "caso": "taxi",
        "regla": "Taxi/Uber de movilidad cotidiana es Transporte; traslado explícitamente asociado a aeropuerto o vacaciones es Viajes y vacaciones.",
    },
    {
        "caso": "computadora",
        "regla": "Computadora personal es Compras personales; si se explicita uso académico, puede clasificarse como Educación según la política del equipo.",
    },
    {
        "caso": "reembolsos_transferencias_fraude",
        "regla": "Reembolsos, transferencias entre cuentas propias, retiros de efectivo, cargos fraudulentos o reversos no deben generarse hasta definir su tratamiento contable en el contrato del sistema.",
    },
]


def aplanar_diccionario(diccionario: dict) -> dict[str, list[str]]:
    """Convierte etiqueta -> concepto -> expresiones al formato plano original."""
    return {
        etiqueta: [
            expresion
            for expresiones in conceptos.values()
            for expresion in expresiones
        ]
        for etiqueta, conceptos in diccionario.items()
    }


def contar_expresiones(diccionario: dict) -> dict[str, dict[str, int]]:
    """Resumen simple para auditar variedad antes de generar el dataset."""
    return {
        etiqueta: {
            "conceptos": len(conceptos),
            "expresiones": sum(len(expresiones) for expresiones in conceptos.values()),
        }
        for etiqueta, conceptos in diccionario.items()
    }


if __name__ == "__main__":
    print("Tipos de movimiento:", contar_expresiones(DICCIONARIO_TIPO_MOVIMIENTO))
    print("Categorías:", contar_expresiones(DICCIONARIO_CATEGORIA))
