# **Notebook entregable**

Incluye:

- Exploración y limpieza de datos.
- Tratamiento de variables financieras y textual
- Ingeniería de características
- Clasificación de gastos
- Análisis financiero
- Entrenamiento y evaluación de modelos
- Métricas de desempeño
- Serialización de modelos (.pkl o .joblib)

## **Exploración de datos**

### **Carga de librerías y dataset**

In [24]:
import pandas as pd
import unicodedata

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 100)

ruta = "dataset_finance_ai.csv"

df = pd.read_csv(ruta)

print("Dimensiones:", df.shape)
df.head()

Dimensiones: (4676, 13)


,user_id,nombre,arquetipo_perfil,periodo_inicio,periodo_fin,fecha,descripcion,monto,tipo_movimiento,categoria,grupo,tipo_pago,tasa_de_interes_de_la_tarjeta
0,110504306,Valentina Romero,Usuario con ingresos estacionales,2026-07-01,2026-07-31,2026-07-01,cosas para cocinar,164.68,Consumo,Alimentación,Esencial,Efectivo,NaN
1,110504306,Valentina Romero,Usuario con ingresos estacionales,2026-07-01,2026-07-31,2026-07-01,apoyo a un familiar,238.45,Consumo,Otros,NaN,Tarjeta de débito,NaN
2,110504306,Valentina Romero,Usuario con ingresos estacionales,2026-07-01,2026-07-31,2026-07-02,cambio de aceite,602.64,Consumo,Transporte,Esencial,Transferencia bancaria,NaN
3,110504306,Valentina Romero,Usuario con ingresos estacionales,2026-07-01,2026-07-31,2026-07-02,venta por internet,1935.92,Ingreso,NaN,NaN,Transferencia bancaria,NaN
4,110504306,Valentina Romero,Usuario con ingresos estacionales,2026-07-01,2026-07-31,2026-07-03,compré pescado,351.15,Consumo,Alimentación,Esencial,Efectivo,NaN


In [2]:
df.tail()

,user_id,nombre,arquetipo_perfil,periodo_inicio,periodo_fin,fecha,descripcion,monto,tipo_movimiento,categoria,grupo,tipo_pago,tasa_de_interes_de_la_tarjeta
4671,975413421,Andrea Flores,Usuario que pierde su empleo,2026-07-01,2026-07-31,2026-07-27,frutas y verduras,743.64,Consumo,Alimentación,Esencial,Tarjeta de crédito,41.9
4672,975413421,Andrea Flores,Usuario que pierde su empleo,2026-07-01,2026-07-31,2026-07-28,fui por el mandado,702.10,Consumo,Alimentación,Esencial,Tarjeta de débito,NaN
4673,975413421,Andrea Flores,Usuario que pierde su empleo,2026-07-01,2026-07-31,2026-07-28,pintura para la casa,1074.26,Consumo,Vivienda,Esencial,Tarjeta de débito,NaN
4674,975413421,Andrea Flores,Usuario que pierde su empleo,2026-07-01,2026-07-31,2026-07-29,supermercado,268.38,Consumo,Alimentación,Esencial,Transferencia bancaria,NaN
4675,975413421,Andrea Flores,Usuario que pierde su empleo,2026-07-01,2026-07-31,2026-07-29,compré sandalias,470.92,Consumo,Compras personales,Discrecional,Efectivo,NaN


### **Exploración de las columnas**

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4676 entries, 0 to 4675
Data columns (total 13 columns):
 #   Column                         Non-Null Count  Dtype  
---  ------                         --------------  -----  
 0   user_id                        4676 non-null   int64  
 1   nombre                         4676 non-null   str    
 2   arquetipo_perfil               4676 non-null   str    
 3   periodo_inicio                 4676 non-null   str    
 4   periodo_fin                    4676 non-null   str    
 5   fecha                          4676 non-null   str    
 6   descripcion                    4676 non-null   str    
 7   monto                          4676 non-null   float64
 8   tipo_movimiento                4676 non-null   str    
 9   categoria                      4148 non-null   str    
 10  grupo                          4021 non-null   str    
 11  tipo_pago                      4676 non-null   str    
 12  tasa_de_interes_de_la_tarjeta  824 non-null    float64
dtyp

In [6]:
print("Número de filas:", df.shape[0])
print("Número de columnas:", df.shape[1])
print("Número de usuarios:", df["user_id"].nunique())

print("\nColumnas:")
print(df.columns.tolist())

Número de filas: 4676
Número de columnas: 13
Número de usuarios: 110

Columnas:
['user_id', 'nombre', 'arquetipo_perfil', 'periodo_inicio', 'periodo_fin', 'fecha', 'descripcion', 'monto', 'tipo_movimiento', 'categoria', 'grupo', 'tipo_pago', 'tasa_de_interes_de_la_tarjeta']


In [8]:
df.sample(10, random_state=42)

,user_id,nombre,arquetipo_perfil,periodo_inicio,periodo_fin,fecha,descripcion,monto,tipo_movimiento,categoria,grupo,tipo_pago,tasa_de_interes_de_la_tarjeta
2493,620531776,Emiliano García,Usuario con varias señales de estrés financiero simultáneas,2026-07-01,2026-07-31,2026-07-30,leche y huevos,427.33,Consumo,Alimentación,Esencial,Tarjeta de crédito,63.2
33,110504306,Valentina Romero,Usuario con ingresos estacionales,2026-07-01,2026-07-31,2026-07-24,seguro del coche,131.58,Consumo,Transporte,Esencial,Tarjeta de débito,NaN
3683,814760565,Eduardo López,Usuario con ingresos bajos pero excelente administración,2026-07-01,2026-07-31,2026-07-25,abono a la hipoteca,276.29,Pago de deuda,NaN,NaN,Transferencia bancaria,NaN
4129,864934246,Santiago Chávez,Usuario con ingresos variables,2026-07-01,2026-07-31,2026-07-14,cambio de aceite,229.33,Consumo,Transporte,Esencial,Tarjeta de débito,NaN
3193,732100362,Carolina Díaz,Usuario con ingresos altos pero sin ahorro,2026-07-01,2026-07-31,2026-07-25,camión,438.92,Consumo,Transporte,Esencial,Tarjeta de débito,NaN
4374,897310301,Emiliano Torres,Usuario que paga siempre el mínimo de su tarjeta,2026-07-01,2026-07-31,2026-07-15,pago de la quincena,3721.21,Ingreso,NaN,NaN,Transferencia bancaria,NaN
2716,681738546,Leonardo López,Usuario que gasta más de lo que gana,2026-07-01,2026-07-31,2026-07-28,perfume,756.21,Consumo,Compras personales,Discrecional,Efectivo,NaN
2303,601498537,Valentina García,Usuario que paga siempre el mínimo de su tarjeta,2026-07-01,2026-07-31,2026-07-14,pago de electricidad,594.97,Consumo,Vivienda,Esencial,Tarjeta de débito,NaN
3307,749041971,Javier Domínguez,Usuario que pierde su empleo,2026-07-01,2026-07-31,2026-07-07,verdura para la semana,308.45,Consumo,Alimentación,Esencial,Tarjeta de débito,NaN
2875,684892124,Javier Reyes,Usuario que invierte mientras utiliza crédito para gastos básicos,2026-07-01,2026-07-31,2026-07-31,invertí en CETES,1968.63,Ahorro e inversión,NaN,NaN,Transferencia bancaria,NaN


## **Limpieza de datos**

### **Exploración de valores nulos**

In [11]:
nulos = pd.DataFrame({
    "nulos": df.isna().sum(),
    "porcentaje": (df.isna().mean() * 100).round(2)
})

nulos

,nulos,porcentaje
user_id,0,0.00
nombre,0,0.00
periodo_inicio,0,0.00
periodo_fin,0,0.00
fecha,0,0.00
descripcion,0,0.00
monto,0,0.00
tipo_movimiento,0,0.00
categoria,528,11.29
grupo,655,14.01


In [12]:
df[["categoria", "grupo", "tasa_de_interes_de_la_tarjeta"]].isna().sum()

categoria                         528
grupo                             655
tasa_de_interes_de_la_tarjeta    3852
dtype: int64

##### **nan en categoria**

In [14]:
pd.crosstab(
    df["tipo_movimiento"],
    df["categoria"].isna(),
    margins=True
)

categoria,False,True,All
tipo_movimiento,,,
Ahorro e inversión,0,109,109
Consumo,4148,0,4148
Ingreso,0,255,255
Pago de deuda,0,164,164
All,4148,528,4676


In [15]:
df[
    (df["tipo_movimiento"] != "Consumo") &
    (df["categoria"].notna())
].shape[0]

0

Los nan se encuentran presentes en Ahorro e Inversión, Ingreso y Pago de deuda, las cuales son dimensiones que estructuralmente no tienen categroría porque no son consumo.

##### **nan en grupo**

In [17]:
pd.crosstab(
    df["tipo_movimiento"],
    df["grupo"].isna(),
    margins=True
)

grupo,False,True,All
tipo_movimiento,,,
Ahorro e inversión,0,109,109
Consumo,4021,127,4148
Ingreso,0,255,255
Pago de deuda,0,164,164
All,4021,655,4676


In [18]:
df[df["categoria"] == "Otros"]["grupo"].value_counts(dropna=False)

grupo
NaN    127
Name: count, dtype: int64

Hay un total de 655 nan en grupo. 528 son de las dimensiones diferentes a consumo que no necesitan "categoría" y por lo tanto no pueden clasificarse en "esencial" o "discrecional" + 127 pertenecientes a "otros", que por default no puedes categorizarse.

Por lo tanto, al no ser errores, no deben imputarse, puesto que tienen sentido lógico dentro de la estructura.


#### **Exploración tasa de interés**

Tada de interes unicamente sale cuando tipo_pago = tarjeta de credito

In [19]:
pd.crosstab(
    df["tipo_pago"],
    df["tasa_de_interes_de_la_tarjeta"].isna(),
    margins=True
)

tasa_de_interes_de_la_tarjeta,False,True,All
tipo_pago,,,
Efectivo,0,573,573
Tarjeta de crédito,824,0,824
Tarjeta de débito,0,1867,1867
Transferencia bancaria,0,1412,1412
All,824,3852,4676


In [20]:
credito_sin_tasa = df[
    (df["tipo_pago"] == "Tarjeta de crédito") &
    (df["tasa_de_interes_de_la_tarjeta"].isna())
]

tasa_sin_credito = df[
    (df["tipo_pago"] != "Tarjeta de crédito") &
    (df["tasa_de_interes_de_la_tarjeta"].notna())
]

print("Créditos sin tasa:", len(credito_sin_tasa))
print("Operaciones no crédito con tasa:", len(tasa_sin_credito))

Créditos sin tasa: 0
Operaciones no crédito con tasa: 0


No se debe imputar esta variable puesto que en todos los casos la tasa de interés sí aparece unicamente en entradas de tarjeta de credito como tipo de pago.

#### **Duplicados**

In [21]:
duplicados = df.duplicated().sum()

print("Registros duplicados:", duplicados)

Registros duplicados: 0


#### **Validación de identificadores del usuario**

In [22]:
print("Usuarios únicos:", df["user_id"].nunique())
print("IDs nulos:", df["user_id"].isna().sum())

Usuarios únicos: 110
IDs nulos: 0


In [25]:
validacion_usuario = (
    df.groupby("user_id")
      .agg(
          nombres=("nombre", "nunique"),
          perfiles=("arquetipo_perfil", "nunique")
      )
)

validacion_usuario.describe()

,nombres,perfiles
count,110.0,110.0
mean,1.0,1.0
std,0.0,0.0
min,1.0,1.0
25%,1.0,1.0
50%,1.0,1.0
75%,1.0,1.0
max,1.0,1.0


In [26]:
validacion_usuario[
    (validacion_usuario["nombres"] > 1) |
    (validacion_usuario["perfiles"] > 1)
]

,nombres,perfiles
user_id,,


#### **Validación de fechas**

In [32]:
columnas_fecha = [
    "periodo_inicio",
    "periodo_fin",
    "fecha"
]

for columna in columnas_fecha:
    df[columna] = pd.to_datetime(
        df[columna],
        format="%d-%m-%Y",
        errors="raise"
    )

In [34]:
for columna in columnas_fecha:
    print(
        columna,
        df[columna].min(),
        df[columna].max()
    )

periodo_inicio 2026-07-01 00:00:00 2026-07-01 00:00:00
periodo_fin 2026-07-31 00:00:00 2026-07-31 00:00:00
fecha 2026-07-01 00:00:00 2026-07-31 00:00:00


In [35]:
fuera_periodo = df[
    (df["fecha"] < df["periodo_inicio"]) |
    (df["fecha"] > df["periodo_fin"])
]

print("Transacciones fuera del periodo:", len(fuera_periodo))

Transacciones fuera del periodo: 0


#### **Validación de monto**

In [36]:
df["monto"] = pd.to_numeric(
    df["monto"],
    errors="raise"
).round(2)

In [37]:
print("Montos nulos:", df["monto"].isna().sum())
print("Montos en cero:", (df["monto"] == 0).sum())
print("Montos negativos:", (df["monto"] < 0).sum())

Montos nulos: 0
Montos en cero: 0
Montos negativos: 0


In [38]:
df["monto"].describe()

count      4676.000000
mean       1375.177825
std        6411.691000
min          20.000000
25%         208.932500
50%         425.475000
75%         852.087500
max      338891.250000
Name: monto, dtype: float64

#### **Outliers**

In [39]:
Q1 = df["monto"].quantile(0.25)
Q3 = df["monto"].quantile(0.75)

IQR = Q3 - Q1

limite_inferior = Q1 - 1.5 * IQR
limite_superior = Q3 + 1.5 * IQR

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Límite inferior:", limite_inferior)
print("Límite superior:", limite_superior)

Q1: 208.9325
Q3: 852.0875
IQR: 643.155
Límite inferior: -755.8
Límite superior: 1816.82


In [40]:
outliers = df[
    (df["monto"] < limite_inferior) |
    (df["monto"] > limite_superior)
]

print("Número de posibles outliers:", len(outliers))

outliers.sort_values(
    "monto",
    ascending=False
).head(20)

Número de posibles outliers: 474


,user_id,nombre,arquetipo_perfil,periodo_inicio,periodo_fin,fecha,descripcion,monto,tipo_movimiento,categoria,grupo,tipo_pago,tasa_de_interes_de_la_tarjeta
2114,549756305,Leonardo Castillo,Usuario que recibe una herencia,2026-07-01,2026-07-31,2026-07-10,herencia recibida,338891.25,Ingreso,NaN,NaN,Transferencia bancaria,NaN
2790,684032941,Paola Jiménez,Usuario con ingresos altos pero sin ahorro,2026-07-01,2026-07-31,2026-07-15,nómina,86753.55,Ingreso,NaN,NaN,Transferencia bancaria,NaN
2822,684032941,Paola Jiménez,Usuario con ingresos altos pero sin ahorro,2026-07-01,2026-07-31,2026-07-30,me pagaron del trabajo,78332.36,Ingreso,NaN,NaN,Transferencia bancaria,NaN
1470,419239795,Paola Flores,Usuario que recibe una herencia,2026-07-01,2026-07-31,2026-07-25,herencia recibida,64554.49,Ingreso,NaN,NaN,Transferencia bancaria,NaN
2123,549756305,Leonardo Castillo,Usuario que recibe una herencia,2026-07-01,2026-07-31,2026-07-16,invertí en un pagaré,52357.48,Ahorro e inversión,NaN,NaN,Transferencia bancaria,NaN
2935,708223369,Fernanda Moreno,Usuario que recibe una herencia,2026-07-01,2026-07-31,2026-07-08,herencia recibida,49401.91,Ingreso,NaN,NaN,Transferencia bancaria,NaN
1291,394877417,Ricardo Moreno,Usuario que invierte mientras utiliza crédito para gastos básicos,2026-07-01,2026-07-31,2026-07-15,depósito de mi sueldo,46717.28,Ingreso,NaN,NaN,Transferencia bancaria,NaN
4583,931697199,Valentina Martínez,Usuario con ingresos estacionales,2026-07-01,2026-07-31,2026-07-18,venta por internet,44769.49,Ingreso,NaN,NaN,Efectivo,NaN
1330,394877417,Ricardo Moreno,Usuario que invierte mientras utiliza crédito para gastos básicos,2026-07-01,2026-07-31,2026-07-30,me cayó la nómina,44211.13,Ingreso,NaN,NaN,Transferencia bancaria,NaN
1114,360278346,Renata Romero,Usuario con deuda creciente pese a ingresos estables,2026-07-01,2026-07-31,2026-07-30,sueldo,41309.01,Ingreso,NaN,NaN,Transferencia bancaria,NaN


El ingreso de $300,000 puede ser extraño respecto a la distribución general pero perfectamente válido para alguno de los perfiles.

In [42]:
#Inspecciona por tipo de movimientos
for tipo, datos in df.groupby("tipo_movimiento"):

    Q1 = datos["monto"].quantile(0.25)
    Q3 = datos["monto"].quantile(0.75)
    IQR = Q3 - Q1

    limite_superior = Q3 + 1.5 * IQR

    n_outliers = (datos["monto"] > limite_superior).sum()

    print(
        f"{tipo}: "
        f"{n_outliers} posibles outliers | "
        f"Límite: ${limite_superior:,.2f} | "
        f"Máximo: ${datos['monto'].max():,.2f}"
    )

Ahorro e inversión: 9 posibles outliers | Límite: $4,448.41 | Máximo: $52,357.48
Consumo: 241 posibles outliers | Límite: $1,427.89 | Máximo: $6,124.07
Ingreso: 14 posibles outliers | Límite: $34,762.49 | Máximo: $338,891.25
Pago de deuda: 11 posibles outliers | Límite: $5,075.07 | Máximo: $15,535.59


#### **Tratamiento de las variables de texto**

In [45]:
columnas_texto = [
    "nombre",
    "arquetipo_perfil",
    "descripcion",
    "tipo_movimiento",
    "categoria",
    "grupo",
    "tipo_pago"
]

for columna in columnas_texto:

    mask = df[columna].notna()

    df.loc[mask, columna] = (
        df.loc[mask, columna]
          .astype(str)
          .str.strip()
          .str.replace(r"\s+", " ", regex=True)
    )

#### **Creación variable descripcion_limpia**

In [46]:
def limpiar_descripcion(texto):

    texto = unicodedata.normalize("NFC", texto)

    texto = texto.strip().lower()

    texto = " ".join(texto.split())

    return texto


df["descripcion_limpia"] = df["descripcion"].apply(
    limpiar_descripcion
)

In [51]:
df[
    ["descripcion", "descripcion_limpia"]
].sample(10, random_state=30)

,descripcion,descripcion_limpia
2489,seguro de gastos médicos,seguro de gastos médicos
1625,fruta para la casa,fruta para la casa
3047,metrobús,metrobús
3911,ingreso por un proyecto,ingreso por un proyecto
2844,pensión del coche,pensión del coche
270,metí dinero a Actinver,metí dinero a actinver
326,fui con el especialista,fui con el especialista
3636,una chamarra,una chamarra
1140,Dropbox,dropbox
1610,refrescos para la casa,refrescos para la casa


#### **Distribución de tipos de movimiento**

In [52]:
conteo_movimientos = (
    df["tipo_movimiento"]
    .value_counts()
    .to_frame("cantidad")
)

conteo_movimientos["porcentaje"] = (
    conteo_movimientos["cantidad"]
    / len(df)
    * 100
).round(2)

conteo_movimientos

,cantidad,porcentaje
tipo_movimiento,,
Consumo,4148,88.71
Ingreso,255,5.45
Pago de deuda,164,3.51
Ahorro e inversión,109,2.33


Aunque hay un fuerte desbalance de clases, esto es normal pues en la vida real, las personas suelen tener muchos más gastos que ingresos. Es decir la cantidad total invertida en gastos/consumo se divide en más partes que la cantidad total del ingreso.

#### **Distribución de categorías de consumo**

In [53]:
df_consumo = df[
    df["tipo_movimiento"] == "Consumo"
].copy()

In [54]:
distribucion_categorias = (
    df_consumo["categoria"]
    .value_counts()
    .to_frame("cantidad")
)

distribucion_categorias["porcentaje"] = (
    distribucion_categorias["cantidad"]
    / len(df_consumo)
    * 100
).round(2)

distribucion_categorias

,cantidad,porcentaje
categoria,,
Alimentación,1609,38.79
Transporte,1064,25.65
Compras personales,327,7.88
Vivienda,261,6.29
Entretenimiento y ocio,224,5.40
Suscripciones digitales,167,4.03
Salud,144,3.47
Educación,140,3.38
Otros,127,3.06


#### **Distribución de grupos**

In [55]:
df_consumo["grupo"].value_counts(
    dropna=False
)

grupo
Esencial        3218
Discrecional     803
NaN              127
Name: count, dtype: int64

In [56]:
df_consumo["grupo"].value_counts(
    normalize=True,
    dropna=False
).mul(100).round(2)

grupo
Esencial        77.58
Discrecional    19.36
NaN              3.06
Name: proportion, dtype: float64

#### **Análisis de montos por movimiento**

In [57]:
df.groupby("tipo_movimiento")["monto"].agg([
    "count",
    "mean",
    "median",
    "std",
    "min",
    "max"
]).round(2)

,count,mean,median,std,min,max
tipo_movimiento,,,,,,
Ahorro e inversión,109,2756.38,1440.66,6245.35,150.83,52357.48
Consumo,4148,534.15,378.54,554.03,20.00,6124.07
Ingreso,255,14079.00,9794.24,23609.02,151.05,338891.25
Pago de deuda,164,1976.10,1281.20,2176.29,101.25,15535.59


#### **Montos por categoría**

In [58]:
df_consumo.groupby("categoria")["monto"].agg([
    "count",
    "mean",
    "median",
    "min",
    "max"
]).round(2).sort_values(
    "median",
    ascending=False
)

,count,mean,median,min,max
categoria,,,,,
Vivienda,261,1362.93,1171.63,20.00,5877.28
Compras personales,327,796.06,637.10,20.00,5167.83
Educación,140,668.07,550.28,33.06,2938.83
Salud,144,522.25,468.97,20.00,1584.36
Otros,127,452.75,389.06,20.00,2494.20
Alimentación,1609,502.61,377.18,20.00,6124.07
Entretenimiento y ocio,224,458.12,369.22,20.00,3516.10
Transporte,1064,375.17,286.18,20.00,3474.53
Viajes y vacaciones,85,309.30,195.00,35.83,1995.80


frecuencia de la categoría ≠ cantidad de dinero gastado

#### **Distribución por medio de pago**

In [60]:
df["tipo_pago"].unique()

<StringArray>
['Efectivo', 'Tarjeta de débito', 'Transferencia bancaria',
 'Tarjeta de crédito']
Length: 4, dtype: str

In [59]:
distribucion_pago = (
    df["tipo_pago"]
    .value_counts()
    .to_frame("cantidad")
)

distribucion_pago["porcentaje"] = (
    distribucion_pago["cantidad"]
    / len(df)
    * 100
).round(2)

distribucion_pago

,cantidad,porcentaje
tipo_pago,,
Tarjeta de débito,1867,39.93
Transferencia bancaria,1412,30.20
Tarjeta de crédito,824,17.62
Efectivo,573,12.25


#### **Análisis de tipo de pago = tarjeta de crédito**

In [61]:
df_credito = df[
    df["tipo_pago"] == "Tarjeta de crédito"
].copy()

In [63]:
df_credito["tasa_de_interes_de_la_tarjeta"].describe().round(2)

count    824.00
mean      39.93
std       12.10
min       14.70
25%       29.70
50%       41.35
75%       49.00
max       63.20
Name: tasa_de_interes_de_la_tarjeta, dtype: float64

#### **Diversidad en las descripciones**

In [64]:
print(
    "Transacciones:",
    len(df)
)

print(
    "Descripciones únicas:",
    df["descripcion"].nunique()
)

print(
    "Descripciones limpias únicas:",
    df["descripcion_limpia"].nunique()
)

Transacciones: 4676
Descripciones únicas: 535
Descripciones limpias únicas: 535


In [65]:
#comprueba la repitición
frecuencia_descripciones = (
    df["descripcion_limpia"]
    .value_counts()
    .reset_index()
)

frecuencia_descripciones.columns = [
    "descripcion_limpia",
    "frecuencia"
]

frecuencia_descripciones.head(20)

,descripcion_limpia,frecuencia
0,agua embotellada,75
1,botanas para la casa,73
2,jugos y agua,69
3,refrescos para la casa,67
4,snacks del súper,65
5,verdura para la semana,61
6,fruta para la casa,60
7,pescado,59
8,frutas y verduras,57
9,compré verduras,54


#### **Contradicciones semánticas**

Comprueba si una descripción tiene diferentes etiquetas

In [67]:
#para tipo de movimiento
conflictos_movimiento = (
    df.groupby("descripcion_limpia")
      ["tipo_movimiento"]
      .nunique()
)

conflictos_movimiento = conflictos_movimiento[
    conflictos_movimiento > 1
]

print(
    "Descripciones con múltiples tipos de movimiento:",
    len(conflictos_movimiento)
)

Descripciones con múltiples tipos de movimiento: 0


In [68]:
#para las categorías
conflictos_categoria = (
    df_consumo.groupby("descripcion_limpia")
              ["categoria"]
              .nunique()
)

conflictos_categoria = conflictos_categoria[
    conflictos_categoria > 1
]

print(
    "Descripciones con múltiples categorías:",
    len(conflictos_categoria)
)

Descripciones con múltiples categorías: 0


#### **Validación final**

In [69]:
print("Dimensiones finales:", df.shape)
print("Usuarios:", df["user_id"].nunique())
print("Duplicados:", df.duplicated().sum())
print("Descripciones vacías:", (df["descripcion_limpia"] == "").sum())
print("Montos <= 0:", (df["monto"] <= 0).sum())

print("\nNulos:")
print(df.isna().sum())

Dimensiones finales: (4676, 14)
Usuarios: 110
Duplicados: 0
Descripciones vacías: 0
Montos <= 0: 0

Nulos:
user_id                             0
nombre                              0
arquetipo_perfil                    0
periodo_inicio                      0
periodo_fin                         0
fecha                               0
descripcion                         0
monto                               0
tipo_movimiento                     0
categoria                         528
grupo                             655
tipo_pago                           0
tasa_de_interes_de_la_tarjeta    3852
descripcion_limpia                  0
dtype: int64


### **Exportación del dataset limpio**

In [70]:
df.to_csv(
    "dataset_finance_ai_110_usuarios_limpio.csv",
    index=False,
    encoding="utf-8"
)

## **Elaboración del Clasificador**

In [40]:
df_clasificacion = df[
    df["tipo_movimiento"] == "Consumo"
].copy()

In [228]:
# ============================================
# Categorías oficiales de consumo del sistema
# ============================================

CATEGORIAS_CONSUMO = [
    "Vivienda",
    "Alimentación",
    "Transporte",
    "Salud",
    "Educación",
    "Entretenimiento y ocio",
    "Suscripciones digitales",
    "Compras personales",
    "Viajes y vacaciones",
    "Otros"
]

In [200]:
PESOS_DIMENSIONES = {

    "balance_financiero": {

        "tasa_de_gasto": 0.50,

        "margen_financiero": 0.50

    },

    "capacidad_de_ahorro": {

        "tasa_de_ahorro": 0.60,

        "aprovechamiento_del_margen_financiero": 0.40

    },

    "endeudamiento": {

        "ratio_de_endeudamiento": 0.40,

        "presion_de_la_deuda": 0.40,

        "costo_promedio_del_endeudamiento": 0.20

    },

    "comportamiento_de_consumo": {

        "indice_de_concentracion_del_gasto": 0.40,

        "predominio_del_gasto": 0.35,

        "diversificacion_del_consumo": 0.25

    }

}

In [208]:
PESOS_PERFIL_FINANCIERO = {

    "balance_financiero": 0.30,

    "capacidad_de_ahorro": 0.25,

    "endeudamiento": 0.25,

    "comportamiento_de_consumo": 0.20

}

In [190]:
def obtener_estado(puntuacion):

    if puntuacion >= 80:
        return "Saludable"

    elif puntuacion >= 50:
        return "En observación"

    else:
        return "En riesgo"

In [230]:
# ==========================================================
# Mapeo de categorías para la salida de la API
# ==========================================================

MAPA_CATEGORIAS_API = {

    "Vivienda":
        "vivienda",

    "Alimentación":
        "alimentacion",

    "Transporte":
        "transporte",

    "Salud":
        "salud",

    "Educación":
        "educacion",

    "Entretenimiento y ocio":
        "entretenimiento_y_ocio",

    "Suscripciones digitales":
        "suscripciones_digitales",

    "Compras personales":
        "compras_personales",

    "Viajes y vacaciones":
        "viajes_y_vacaciones",

    "Otros":
        "otros"

}

# Implementación de motor financiero

## 1.- Recepción de archivo JSON de prueba ya clasificado manualmente 

In [153]:
import json
import random
from pathlib import Path

def cargar_datos_clasificados(carpeta="datos"):
    """
    Selecciona aleatoriamente uno de los archivos JSON clasificados,
    lo convierte a un diccionario y lo devuelve.
    """

    carpeta_json = Path("perfiles_financieros_pruebas_clasificados_para_motor_financiero")

    numero = random.randint(1, 15)

    nombre_archivo = f"{numero:02d}_clasificado_manualmente.json"

    ruta_archivo = carpeta_json / nombre_archivo

    with open(ruta_archivo, "r", encoding="utf-8") as archivo:
        datos = json.load(archivo)

    print(f"Archivo seleccionado: {nombre_archivo}")

    return datos


datos_clasificados = cargar_datos_clasificados()
print (datos_clasificados)

Archivo seleccionado: 14_clasificado_manualmente.json
{'usuario': {'nombre': 'Nicolás Bravo'}, 'periodo': {'inicio': '2026-07-01', 'fin': '2026-07-31'}, 'ingresos': [{'fecha': '2026-07-01', 'descripcion': 'Diseño de sitio web', 'monto': 14000}, {'fecha': '2026-07-02', 'descripcion': 'Proyecto de identidad visual', 'monto': 9500}, {'fecha': '2026-07-03', 'descripcion': 'Consultoría de marketing', 'monto': 7000}, {'fecha': '2026-07-04', 'descripcion': 'Venta de plantillas digitales', 'monto': 3200}], 'transacciones': [{'fecha': '2026-07-02', 'descripcion': 'Renta departamento', 'monto': 7500, 'forma_pago': 'Transferencia bancaria', 'clasificacion': ['Consumo'], 'categoria': 'Vivienda', 'grupo': 'Esencial'}, {'fecha': '2026-07-04', 'descripcion': 'Internet Totalplay', 'monto': 699, 'forma_pago': 'Tarjeta de crédito', 'tasa_de_interes_de_la_tarjeta': 58, 'clasificacion': ['Consumo', 'Pago de deuda'], 'categoria': 'Otros', 'grupo': 'Esencial'}, {'fecha': '2026-07-05', 'descripcion': 'Adobe 

## 2.- Generación de varibles globales

In [167]:
def calcular_ingreso_mensual(datos_clasificados):
    """
    Calcula el ingreso mensual del usuario.

    Parámetros:
        datos_clasificados (dict): Diccionario con la información del usuario.

    Retorna:
        float: Suma de todos los ingresos registrados durante el periodo.
    """

    ingreso_mensual = 0.0

    for ingreso in datos_clasificados["ingresos"]:
        ingreso_mensual += ingreso["monto"]

    return ingreso_mensual

ingreso_mensual = calcular_ingreso_mensual(datos_clasificados)

print(f"Ingreso mensual: ${ingreso_mensual:,.2f}")

Ingreso mensual: $33,700.00


In [168]:
def calcular_consumo_total_mensual(datos_clasificados):
    """
    Calcula el consumo total mensual del usuario.

    Se consideran únicamente las transacciones cuya clasificación
    contenga exclusivamente la etiqueta "Consumo".

    Parámetros:
        datos_clasificados (dict): Diccionario con las transacciones clasificadas.

    Retorna:
        float: Consumo total mensual.
    """

    consumo_total_mensual = 0.0

    for transaccion in datos_clasificados["transacciones"]:

        clasificacion = transaccion["clasificacion"]

        if (
            "Consumo" in clasificacion
            and len(clasificacion) == 1
        ):
            consumo_total_mensual += transaccion["monto"]

    return consumo_total_mensual

consumo_total_mensual = calcular_consumo_total_mensual(datos_clasificados)

print(f"Consumo total mensual: ${consumo_total_mensual:,.2f}")

Consumo total mensual: $12,800.00


In [170]:
def calcular_pago_mensual_de_deudas(datos_clasificados):
    """
    Calcula el pago mensual de deudas del usuario.

    Se consideran todas las transacciones cuya clasificación
    incluya la etiqueta "Pago de deuda", independientemente
    de si también pertenecen a otra clasificación.

    Parámetros:
        datos_clasificados (dict): Diccionario con las transacciones clasificadas.

    Retorna:
        float: Pago mensual de deudas.
    """

    pago_mensual_de_deudas = 0.0

    for transaccion in datos_clasificados["transacciones"]:

        clasificacion = transaccion["clasificacion"]

        if "Pago de deuda" in clasificacion:
            pago_mensual_de_deudas += transaccion["monto"]

    return pago_mensual_de_deudas

pago_mensual_de_deudas = calcular_pago_mensual_de_deudas(datos_clasificados)

print(f"Pago mensual de deudas: ${pago_mensual_de_deudas:,.2f}")

Pago mensual de deudas: $9,914.00


In [171]:
def calcular_ahorro_e_inversion_total(datos_clasificados):
    """
    Calcula el ahorro e inversión total del usuario.

    Se consideran todas las transacciones cuya clasificación
    incluya la etiqueta "Ahorro e inversión".

    Parámetros:
        datos_clasificados (dict): Diccionario con las transacciones clasificadas.

    Retorna:
        float: Ahorro e inversión total.
    """

    ahorro_e_inversion_total = 0.0

    for transaccion in datos_clasificados["transacciones"]:

        clasificacion = transaccion["clasificacion"]

        if "Ahorro e inversión" in clasificacion:
            ahorro_e_inversion_total += transaccion["monto"]

    return ahorro_e_inversion_total

ahorro_e_inversion_total = calcular_ahorro_e_inversion_total(datos_clasificados)

print(f"Ahorro e inversión total: ${ahorro_e_inversion_total:,.2f}")

Ahorro e inversión total: $6,000.00


In [172]:
def calcular_egreso_total(consumo_total_mensual, pago_mensual_de_deudas):
    """
    Calcula el egreso total del usuario.

    El egreso total corresponde a la suma del consumo total mensual
    y el pago mensual de deudas.

    Parámetros:
        consumo_total_mensual (float): Consumo total mensual del usuario.
        pago_mensual_de_deudas (float): Pago mensual de deudas del usuario.

    Retorna:
        float: Egreso total del usuario.
    """

    egreso_total = consumo_total_mensual + pago_mensual_de_deudas

    return egreso_total

egreso_total = calcular_egreso_total(
    consumo_total_mensual,
    pago_mensual_de_deudas
)

print(f"Egreso total: ${egreso_total:,.2f}")

Egreso total: $22,714.00


In [173]:
def calcular_balance_mensual(ingreso_mensual, egreso_total):
    """
    Calcula el balance mensual del usuario.

    El balance mensual corresponde a la diferencia entre el ingreso
    mensual y el egreso total del periodo.

    Parámetros:
        ingreso_mensual (float): Ingreso mensual del usuario.
        egreso_total (float): Egreso total del usuario.

    Retorna:
        float: Balance mensual del usuario.
    """

    balance_mensual = ingreso_mensual - egreso_total

    return balance_mensual

balance_mensual = calcular_balance_mensual(
    ingreso_mensual,
    egreso_total
)

print(f"Balance mensual: ${balance_mensual:,.2f}")

Balance mensual: $10,986.00


In [174]:
def calcular_consumo_total_por_categoria(datos_clasificados):
    """
    Calcula el consumo total por categoría del usuario.

    Se consideran todas las transacciones cuya clasificación
    incluya la etiqueta "Consumo", independientemente de que
    también estén clasificadas como "Pago de deuda".

    Parámetros:
        datos_clasificados (dict): Diccionario con las transacciones clasificadas.

    Retorna:
        float: Consumo total por categoría.
    """

    consumo_total_por_categoria = 0.0

    for transaccion in datos_clasificados["transacciones"]:

        clasificacion = transaccion["clasificacion"]

        if "Consumo" in clasificacion:
            consumo_total_por_categoria += transaccion["monto"]

    return consumo_total_por_categoria

consumo_total_por_categoria = calcular_consumo_total_por_categoria(datos_clasificados)

print(f"Consumo total por categoría: ${consumo_total_por_categoria:,.2f}")

Consumo total por categoría: $19,514.00


In [178]:
def calcular_gasto_por_categoria(datos_clasificados):
    """
    Calcula el gasto acumulado por categoría de consumo.

    Se consideran todas las transacciones cuya clasificación
    incluya la etiqueta "Consumo", independientemente de que
    también estén clasificadas como "Pago de deuda".

    Parámetros:
        datos_clasificados (dict): Diccionario con las transacciones clasificadas.

    Retorna:
        dict: Diccionario con el gasto acumulado por cada categoría.
    """

    # Inicializar todas las categorías en 0.0
    gasto_por_categoria = {
        categoria: 0.0
        for categoria in CATEGORIAS_CONSUMO
    }

    # Recorrer las transacciones
    for transaccion in datos_clasificados["transacciones"]:

        clasificacion = transaccion["clasificacion"]

        if "Consumo" in clasificacion:

            categoria = transaccion["categoria"]

            gasto_por_categoria[categoria] += transaccion["monto"]

    return gasto_por_categoria

gasto_por_categoria = calcular_gasto_por_categoria(datos_clasificados)

print("Gasto por categoría:")

for categoria, monto in gasto_por_categoria.items():
    print(f"{categoria}: ${monto:,.2f}")


Gasto por categoría:
Vivienda: $7,500.00
Alimentación: $2,400.00
Transporte: $1,300.00
Salud: $1,600.00
Educación: $0.00
Entretenimiento y ocio: $780.00
Suscripciones digitales: $0.00
Compras personales: $0.00
Viajes y vacaciones: $0.00
Otros: $5,934.00


In [179]:
def calcular_distribucion_porcentual_gasto(
    gasto_por_categoria,
    consumo_total_por_categoria
):
    """
    Calcula la distribución porcentual del gasto por categoría.

    La distribución porcentual representa el porcentaje que ocupa
    cada categoría respecto al consumo total por categoría.

    Parámetros:
        gasto_por_categoria (dict): Gasto acumulado por categoría.
        consumo_total_por_categoria (float): Consumo total por categoría.

    Retorna:
        dict: Distribución porcentual del gasto por categoría.
    """

    # Inicializar todas las categorías en 0.0
    distribucion_porcentual_gasto = {
        categoria: 0.0
        for categoria in CATEGORIAS_CONSUMO
    }

    # Evitar división entre cero
    if consumo_total_por_categoria == 0.0:
        return distribucion_porcentual_gasto

    # Calcular la distribución porcentual
    for categoria in CATEGORIAS_CONSUMO:

        distribucion_porcentual_gasto[categoria] = (
            gasto_por_categoria[categoria]
            / consumo_total_por_categoria
        ) * 100

    return distribucion_porcentual_gasto

distribucion_porcentual_gasto = calcular_distribucion_porcentual_gasto(
    gasto_por_categoria,
    consumo_total_por_categoria
)

print("Distribución porcentual del gasto:")

for categoria, porcentaje in distribucion_porcentual_gasto.items():
    print(f"{categoria}: {porcentaje:.2f}%")

Distribución porcentual del gasto:
Vivienda: 38.43%
Alimentación: 12.30%
Transporte: 6.66%
Salud: 8.20%
Educación: 0.00%
Entretenimiento y ocio: 4.00%
Suscripciones digitales: 0.00%
Compras personales: 0.00%
Viajes y vacaciones: 0.00%
Otros: 30.41%


In [166]:
def calcular_tasa_interes_promedio_ponderada(datos_clasificados):
    """
    Calcula la tasa de interés promedio ponderada de las compras
    realizadas con tarjeta de crédito.

    El promedio se calcula utilizando el monto de cada transacción
    como peso.

    Parámetros:
        datos_clasificados (dict): Diccionario con las transacciones clasificadas.

    Retorna:
        float: Tasa de interés promedio ponderada.
    """

    monto_total_credito = 0.0
    suma_ponderada = 0.0

    # Recorrer las transacciones
    for transaccion in datos_clasificados["transacciones"]:

        if transaccion["forma_pago"] == "Tarjeta de crédito":

            monto = transaccion["monto"]
            tasa = transaccion["tasa_de_interes_de_la_tarjeta"]

            monto_total_credito += monto
            suma_ponderada += monto * tasa

    # Evitar división entre cero
    if monto_total_credito == 0.0:
        return 0.0

    tasa_interes_promedio_ponderada = (
        suma_ponderada / monto_total_credito
    )

    return tasa_interes_promedio_ponderada

tasa_interes_promedio_ponderada = calcular_tasa_interes_promedio_ponderada(
    datos_clasificados
)

print(
    f"Tasa de interés promedio ponderada: "
    f"{tasa_interes_promedio_ponderada:.2f}%"
)

Tasa de interés promedio ponderada: 58.00%


In [181]:
def calcular_variables_globales(datos_clasificados):
    """
    Calcula todas las variables globales necesarias para el
    motor de análisis financiero.

    Parámetros:
        datos_clasificados (dict): Diccionario con las transacciones clasificadas.

    Retorna:
        dict: Diccionario con todas las variables globales.
    """

    # Variables obtenidas directamente del diccionario
    ingreso_mensual = calcular_ingreso_mensual(datos_clasificados)

    consumo_total_mensual = calcular_consumo_total_mensual(
        datos_clasificados
    )

    pago_mensual_de_deudas = calcular_pago_mensual_de_deudas(
        datos_clasificados
    )

    ahorro_e_inversion_total = calcular_ahorro_e_inversion_total(
        datos_clasificados
    )

    consumo_total_por_categoria = calcular_consumo_total_por_categoria(
        datos_clasificados
    )

    gasto_por_categoria = calcular_gasto_por_categoria(
        datos_clasificados
    )

    tasa_interes_promedio_ponderada = (
        calcular_tasa_interes_promedio_ponderada(
            datos_clasificados
        )
    )

    # Variables derivadas
    egreso_total = calcular_egreso_total(
        consumo_total_mensual,
        pago_mensual_de_deudas
    )

    balance_mensual = calcular_balance_mensual(
        ingreso_mensual,
        egreso_total
    )

    distribucion_porcentual_gasto = (
        calcular_distribucion_porcentual_gasto(
            gasto_por_categoria,
            consumo_total_por_categoria
        )
    )

    # Construcción del diccionario de salida
    variables_globales = {

        "ingreso_mensual": ingreso_mensual,

        "consumo_total_mensual": consumo_total_mensual,

        "pago_mensual_de_deudas": pago_mensual_de_deudas,

        "ahorro_e_inversion_total": ahorro_e_inversion_total,

        "egreso_total": egreso_total,

        "balance_mensual": balance_mensual,

        "consumo_total_por_categoria": consumo_total_por_categoria,

        "gasto_por_categoria": gasto_por_categoria,

        "distribucion_porcentual_gasto": (
            distribucion_porcentual_gasto
        ),

        "tasa_interes_promedio_ponderada": (
            tasa_interes_promedio_ponderada
        )
    }

    return variables_globales

variables_globales = calcular_variables_globales(
    datos_clasificados
)

for nombre, valor in variables_globales.items():
    print(f"{nombre}:")
    print(valor)
    print()

print (variables_globales)


ingreso_mensual:
33700.0

consumo_total_mensual:
12800.0

pago_mensual_de_deudas:
9914.0

ahorro_e_inversion_total:
6000.0

egreso_total:
22714.0

balance_mensual:
10986.0

consumo_total_por_categoria:
19514.0

gasto_por_categoria:
{'Vivienda': 7500.0, 'Alimentación': 2400.0, 'Transporte': 1300.0, 'Salud': 1600.0, 'Educación': 0.0, 'Entretenimiento y ocio': 780.0, 'Suscripciones digitales': 0.0, 'Compras personales': 0.0, 'Viajes y vacaciones': 0.0, 'Otros': 5934.0}

distribucion_porcentual_gasto:
{'Vivienda': 38.43394486010044, 'Alimentación': 12.298862355232142, 'Transporte': 6.661883775750743, 'Salud': 8.199241570154761, 'Educación': 0.0, 'Entretenimiento y ocio': 3.997130265450446, 'Suscripciones digitales': 0.0, 'Compras personales': 0.0, 'Viajes y vacaciones': 0.0, 'Otros': 30.408937173311468}

tasa_interes_promedio_ponderada:
58.0

{'ingreso_mensual': 33700.0, 'consumo_total_mensual': 12800.0, 'pago_mensual_de_deudas': 9914.0, 'ahorro_e_inversion_total': 6000.0, 'egreso_total': 

## Generación de indicadores financieros por  cada una de las 4 dimenciones  

In [183]:
def calcular_indicadores_balance_financiero(variables_globales):
    """
    Calcula los indicadores de la dimensión Balance Financiero.

    Parámetros:
        variables_globales (dict): Diccionario con las variables
        globales calculadas previamente.

    Retorna:
        dict: Diccionario con los indicadores de la dimensión
        Balance Financiero.
    """

    ingreso_mensual = variables_globales["ingreso_mensual"]
    egreso_total = variables_globales["egreso_total"]
    balance_mensual = variables_globales["balance_mensual"]

    # Indicador 1: Balance mensual
    indicador_balance_mensual = balance_mensual

    # Indicador 2: Tasa de gasto
    if ingreso_mensual == 0.0:
        indicador_tasa_de_gasto = 0.0
    else:
        indicador_tasa_de_gasto = (
            egreso_total / ingreso_mensual
        )

    # Indicador 3: Margen financiero
    if ingreso_mensual == 0.0:
        indicador_margen_financiero = 0.0
    else:
        indicador_margen_financiero = (
            balance_mensual / ingreso_mensual
        )

    indicadores_balance_financiero = {

        "balance_mensual": indicador_balance_mensual,

        "tasa_de_gasto": indicador_tasa_de_gasto,

        "margen_financiero": indicador_margen_financiero

    }

    return indicadores_balance_financiero

indicadores_balance_financiero = (
    calcular_indicadores_balance_financiero(
        variables_globales
    )
)

print("Indicadores de Balance Financiero:\n")

for indicador, valor in indicadores_balance_financiero.items():
    print(f"{indicador}: {valor}")

print (indicadores_balance_financiero)

Indicadores de Balance Financiero:

balance_mensual: 10986.0
tasa_de_gasto: 0.6740059347181009
margen_financiero: 0.3259940652818991
{'balance_mensual': 10986.0, 'tasa_de_gasto': 0.6740059347181009, 'margen_financiero': 0.3259940652818991}


In [184]:
def calcular_indicadores_capacidad_ahorro(variables_globales):
    """
    Calcula los indicadores de la dimensión Capacidad de Ahorro.

    Parámetros:
        variables_globales (dict): Diccionario con las variables
        globales calculadas previamente.

    Retorna:
        dict: Diccionario con los indicadores de la dimensión
        Capacidad de Ahorro.
    """

    ingreso_mensual = variables_globales["ingreso_mensual"]
    ahorro_e_inversion_total = variables_globales["ahorro_e_inversion_total"]
    balance_mensual = variables_globales["balance_mensual"]

    # Indicador 1: Tasa de ahorro
    if ingreso_mensual == 0.0:
        indicador_tasa_de_ahorro = 0.0
    else:
        indicador_tasa_de_ahorro = (
            ahorro_e_inversion_total / ingreso_mensual
        )

    # Indicador 2: Ahorro e inversión del periodo
    indicador_ahorro_e_inversion_del_periodo = (
        ahorro_e_inversion_total
    )

    # Indicador 3: Aprovechamiento del margen financiero
    if balance_mensual <= 0.0:
        indicador_aprovechamiento_del_margen_financiero = 0.0
    else:
        indicador_aprovechamiento_del_margen_financiero = (
            ahorro_e_inversion_total / balance_mensual
        )

    indicadores_capacidad_ahorro = {

        "tasa_de_ahorro": indicador_tasa_de_ahorro,

        "ahorro_e_inversion_del_periodo":
            indicador_ahorro_e_inversion_del_periodo,

        "aprovechamiento_del_margen_financiero":
            indicador_aprovechamiento_del_margen_financiero

    }

    return indicadores_capacidad_ahorro

indicadores_capacidad_ahorro = (
    calcular_indicadores_capacidad_ahorro(
        variables_globales
    )
)

print("Indicadores de Capacidad de Ahorro:\n")

for indicador, valor in indicadores_capacidad_ahorro.items():
    print(f"{indicador}: {valor}")

Indicadores de Capacidad de Ahorro:

tasa_de_ahorro: 0.17804154302670624
ahorro_e_inversion_del_periodo: 6000.0
aprovechamiento_del_margen_financiero: 0.5461496450027308


In [185]:
def calcular_indicadores_endeudamiento(variables_globales):
    """
    Calcula los indicadores de la dimensión Endeudamiento.

    Parámetros:
        variables_globales (dict): Diccionario con las variables
        globales calculadas previamente.

    Retorna:
        dict: Diccionario con los indicadores de la dimensión
        Endeudamiento.
    """

    ingreso_mensual = variables_globales["ingreso_mensual"]
    pago_mensual_de_deudas = variables_globales["pago_mensual_de_deudas"]
    egreso_total = variables_globales["egreso_total"]
    tasa_interes_promedio_ponderada = (
        variables_globales["tasa_interes_promedio_ponderada"]
    )

    # Indicador 1: Ratio de endeudamiento
    if ingreso_mensual == 0.0:
        indicador_ratio_de_endeudamiento = 0.0
    else:
        indicador_ratio_de_endeudamiento = (
            pago_mensual_de_deudas / ingreso_mensual
        )

    # Indicador 2: Monto destinado al pago de deudas
    indicador_monto_destinado_al_pago_de_deudas = (
        pago_mensual_de_deudas
    )

    # Indicador 3: Presión de la deuda
    if egreso_total == 0.0:
        indicador_presion_de_la_deuda = 0.0
    else:
        indicador_presion_de_la_deuda = (
            pago_mensual_de_deudas / egreso_total
        )

    # Indicador 4: Costo promedio del endeudamiento
    indicador_costo_promedio_del_endeudamiento = (
        tasa_interes_promedio_ponderada
    )

    indicadores_endeudamiento = {

        "ratio_de_endeudamiento":
            indicador_ratio_de_endeudamiento,

        "monto_destinado_al_pago_de_deudas":
            indicador_monto_destinado_al_pago_de_deudas,

        "presion_de_la_deuda":
            indicador_presion_de_la_deuda,

        "costo_promedio_del_endeudamiento":
            indicador_costo_promedio_del_endeudamiento

    }

    return indicadores_endeudamiento

indicadores_endeudamiento = (
    calcular_indicadores_endeudamiento(
        variables_globales
    )
)

print("Indicadores de Endeudamiento:\n")

for indicador, valor in indicadores_endeudamiento.items():
    print(f"{indicador}: {valor}")

Indicadores de Endeudamiento:

ratio_de_endeudamiento: 0.2941839762611276
monto_destinado_al_pago_de_deudas: 9914.0
presion_de_la_deuda: 0.43647089900501895
costo_promedio_del_endeudamiento: 58.0


In [186]:
def calcular_indicadores_comportamiento_consumo(
    variables_globales,
    datos_clasificados
):
    """
    Calcula los indicadores de la dimensión Comportamiento de Consumo.

    Parámetros:
        variables_globales (dict): Diccionario con las variables
        globales calculadas previamente.
        datos_clasificados (dict): Diccionario con las transacciones
        clasificadas.

    Retorna:
        dict: Diccionario con los indicadores de la dimensión
        Comportamiento de Consumo.
    """

    distribucion_porcentual_gasto = (
        variables_globales["distribucion_porcentual_gasto"]
    )

    consumo_total_por_categoria = (
        variables_globales["consumo_total_por_categoria"]
    )

    gasto_por_categoria = (
        variables_globales["gasto_por_categoria"]
    )

    # ==========================================================
    # Indicador 1: Distribución del gasto por categoría
    # ==========================================================

    indicador_distribucion_del_gasto_por_categoria = (
        distribucion_porcentual_gasto
    )

    # ==========================================================
    # Indicador 2: Índice de concentración del gasto
    # (HHI normalizado)
    # ==========================================================

    if consumo_total_por_categoria == 0.0:

        indicador_indice_de_concentracion_del_gasto = 0.0

    else:

        hhi = 0.0

        for porcentaje in distribucion_porcentual_gasto.values():

            proporcion = porcentaje / 100

            hhi += proporcion ** 2

        n = len(CATEGORIAS_CONSUMO)

        indicador_indice_de_concentracion_del_gasto = (
            (hhi - (1 / n))
            /
            (1 - (1 / n))
        )

    # ==========================================================
    # Perfil de consumo
    # ==========================================================

    # ----------------------------------------------------------
    # Indicador de consumo 1: Predominio del gasto
    # ----------------------------------------------------------

    gasto_esencial = 0.0
    gasto_discrecional = 0.0

    for transaccion in datos_clasificados["transacciones"]:

        if "Consumo" in transaccion["clasificacion"]:

            if transaccion["grupo"] == "Esencial":

                gasto_esencial += transaccion["monto"]

            elif transaccion["grupo"] == "Discrecional":

                gasto_discrecional += transaccion["monto"]

    if consumo_total_por_categoria == 0.0:

        indicador_predominio_del_gasto = (
            "Balance entre gastos esenciales y discrecionales"
        )

    else:

        porcentaje_esencial = (
            gasto_esencial / consumo_total_por_categoria
        )

        porcentaje_discrecional = (
            gasto_discrecional / consumo_total_por_categoria
        )

        if porcentaje_esencial >= 0.60:

            indicador_predominio_del_gasto = (
                "Predominio en gastos esenciales"
            )

        elif porcentaje_discrecional >= 0.60:

            indicador_predominio_del_gasto = (
                "Predominio en gastos discrecionales"
            )

        else:

            indicador_predominio_del_gasto = (
                "Balance entre gastos esenciales y discrecionales"
            )

    # ----------------------------------------------------------
    # Indicador de consumo 2: Tipo de consumo
    # ----------------------------------------------------------

    indice = indicador_indice_de_concentracion_del_gasto

    if indice <= 0.33:

        indicador_tipo_de_consumo = (
            "Consumo equilibrado"
        )

    elif indice <= 0.66:

        indicador_tipo_de_consumo = (
            "Consumo moderadamente concentrado"
        )

    else:

        indicador_tipo_de_consumo = (
            "Consumo altamente concentrado"
        )

    # ----------------------------------------------------------
    # Indicador de consumo 3: Diversificación del consumo
    # ----------------------------------------------------------

    categorias_utilizadas = 0

    for monto in gasto_por_categoria.values():

        if monto > 0:

            categorias_utilizadas += 1

    if categorias_utilizadas >= 5:

        indicador_diversificacion_del_consumo = (
            "Consumo diversificado"
        )

    else:

        indicador_diversificacion_del_consumo = (
            "Consumo poco diversificado"
        )

    # ----------------------------------------------------------
    # Indicador de consumo 4: Categoría predominante
    # ----------------------------------------------------------

    if consumo_total_por_categoria == 0.0:

        indicador_categoria_predominante = "Ninguna"

    else:

        indicador_categoria_predominante = max(
            distribucion_porcentual_gasto,
            key=distribucion_porcentual_gasto.get
        )

    indicadores_comportamiento_consumo = {

        "distribucion_del_gasto_por_categoria":
            indicador_distribucion_del_gasto_por_categoria,

        "indice_de_concentracion_del_gasto":
            indicador_indice_de_concentracion_del_gasto,

        "perfil_de_consumo": {

            "predominio_del_gasto":
                indicador_predominio_del_gasto,

            "tipo_de_consumo":
                indicador_tipo_de_consumo,

            "diversificacion_del_consumo":
                indicador_diversificacion_del_consumo,

            "categoria_predominante":
                indicador_categoria_predominante
        }

    }

    return indicadores_comportamiento_consumo

indicadores_comportamiento_consumo = (
    calcular_indicadores_comportamiento_consumo(
        variables_globales,
        datos_clasificados
    )
)

from pprint import pprint

print("Indicadores de Comportamiento de Consumo:\n")

pprint(indicadores_comportamiento_consumo)

Indicadores de Comportamiento de Consumo:

{'distribucion_del_gasto_por_categoria': {'Alimentación': 12.298862355232142,
                                          'Compras personales': 0.0,
                                          'Educación': 0.0,
                                          'Entretenimiento y ocio': 3.997130265450446,
                                          'Otros': 30.408937173311468,
                                          'Salud': 8.199241570154761,
                                          'Suscripciones digitales': 0.0,
                                          'Transporte': 6.661883775750743,
                                          'Viajes y vacaciones': 0.0,
                                          'Vivienda': 38.43394486010044},
 'indice_de_concentracion_del_gasto': 0.18674654454210401,
 'perfil_de_consumo': {'categoria_predominante': 'Vivienda',
                       'diversificacion_del_consumo': 'Consumo diversificado',
                       'predom

In [187]:
def calcular_indicadores_financieros(
    variables_globales,
    datos_clasificados
):
    """
    Calcula todos los indicadores financieros del sistema.

    Parámetros:
        variables_globales (dict): Diccionario con las variables
        globales calculadas previamente.
        datos_clasificados (dict): Diccionario con las transacciones
        clasificadas.

    Retorna:
        dict: Diccionario con los indicadores financieros de las
        cuatro dimensiones.
    """

    indicadores_balance_financiero = (
        calcular_indicadores_balance_financiero(
            variables_globales
        )
    )

    indicadores_capacidad_ahorro = (
        calcular_indicadores_capacidad_ahorro(
            variables_globales
        )
    )

    indicadores_endeudamiento = (
        calcular_indicadores_endeudamiento(
            variables_globales
        )
    )

    indicadores_comportamiento_consumo = (
        calcular_indicadores_comportamiento_consumo(
            variables_globales,
            datos_clasificados
        )
    )

    indicadores_financieros = {

        "balance_financiero":
            indicadores_balance_financiero,

        "capacidad_de_ahorro":
            indicadores_capacidad_ahorro,

        "endeudamiento":
            indicadores_endeudamiento,

        "comportamiento_de_consumo":
            indicadores_comportamiento_consumo

    }

    return indicadores_financieros

indicadores_financieros = (
    calcular_indicadores_financieros(
        variables_globales,
        datos_clasificados
    )
)

from pprint import pprint

print("Indicadores financieros:\n")

pprint(indicadores_financieros)

Indicadores financieros:

{'balance_financiero': {'balance_mensual': 10986.0,
                        'margen_financiero': 0.3259940652818991,
                        'tasa_de_gasto': 0.6740059347181009},
 'capacidad_de_ahorro': {'ahorro_e_inversion_del_periodo': 6000.0,
                         'aprovechamiento_del_margen_financiero': 0.5461496450027308,
                         'tasa_de_ahorro': 0.17804154302670624},
 'comportamiento_de_consumo': {'distribucion_del_gasto_por_categoria': {'Alimentación': 12.298862355232142,
                                                                        'Compras personales': 0.0,
                                                                        'Educación': 0.0,
                                                                        'Entretenimiento y ocio': 3.997130265450446,
                                                                        'Otros': 30.408937173311468,
                                                              

## Obtención de la puntcuación y estado de cada dimensión

In [192]:
def evaluar_balance_financiero(indicadores_financieros):
    """
    Evalúa la dimensión Balance Financiero.

    Parámetros:
        indicadores_financieros (dict): Diccionario con los indicadores
        financieros previamente calculados.

    Retorna:
        dict: Diccionario con la puntuación y estado de la dimensión.
    """

    indicadores = indicadores_financieros["balance_financiero"]

    tasa_de_gasto = indicadores["tasa_de_gasto"]
    margen_financiero = indicadores["margen_financiero"]

    # ==========================================================
    # Puntuación del indicador: Tasa de gasto
    # ==========================================================

    if tasa_de_gasto <= 0.50:
        puntuacion_tasa_de_gasto = 100

    elif tasa_de_gasto <= 0.60:
        puntuacion_tasa_de_gasto = 90

    elif tasa_de_gasto <= 0.70:
        puntuacion_tasa_de_gasto = 80

    elif tasa_de_gasto <= 0.80:
        puntuacion_tasa_de_gasto = 70

    elif tasa_de_gasto <= 0.90:
        puntuacion_tasa_de_gasto = 60

    elif tasa_de_gasto <= 1.00:
        puntuacion_tasa_de_gasto = 50

    else:
        puntuacion_tasa_de_gasto = 0

    # ==========================================================
    # Puntuación del indicador: Margen financiero
    # ==========================================================

    if margen_financiero >= 0.50:
        puntuacion_margen_financiero = 100

    elif margen_financiero >= 0.40:
        puntuacion_margen_financiero = 90

    elif margen_financiero >= 0.30:
        puntuacion_margen_financiero = 80

    elif margen_financiero >= 0.20:
        puntuacion_margen_financiero = 70

    elif margen_financiero >= 0.10:
        puntuacion_margen_financiero = 60

    elif margen_financiero >= 0.00:
        puntuacion_margen_financiero = 50

    else:
        puntuacion_margen_financiero = 0

    # ==========================================================
    # Puntuación de la dimensión
    # ==========================================================

    pesos = PESOS_DIMENSIONES["balance_financiero"]

    puntuacion_dimension = round(

        (puntuacion_tasa_de_gasto *
         pesos["tasa_de_gasto"])

        +

        (puntuacion_margen_financiero *
         pesos["margen_financiero"])

    )

    # ==========================================================
    # Estado de la dimensión
    # ==========================================================

    estado = obtener_estado(puntuacion_dimension)

    evaluacion_balance_financiero = {

        "puntuacion": puntuacion_dimension,

        "estado": estado

    }

    return evaluacion_balance_financiero

evaluacion_balance_financiero = (
    evaluar_balance_financiero(
        indicadores_financieros
    )
)

print(evaluacion_balance_financiero)

{'puntuacion': 80, 'estado': 'Saludable'}


In [195]:
def evaluar_capacidad_de_ahorro(indicadores_financieros):
    """
    Evalúa la dimensión Capacidad de Ahorro.

    Parámetros:
        indicadores_financieros (dict): Diccionario con los indicadores
        financieros previamente calculados.

    Retorna:
        dict: Diccionario con la puntuación y estado de la dimensión.
    """

    indicadores = indicadores_financieros["capacidad_de_ahorro"]

    tasa_de_ahorro = indicadores["tasa_de_ahorro"]

    aprovechamiento_del_margen_financiero = (
        indicadores["aprovechamiento_del_margen_financiero"]
    )

    # ==========================================================
    # Puntuación del indicador: Tasa de ahorro
    # ==========================================================

    if tasa_de_ahorro >= 0.30:
        puntuacion_tasa_de_ahorro = 100

    elif tasa_de_ahorro >= 0.25:
        puntuacion_tasa_de_ahorro = 90

    elif tasa_de_ahorro >= 0.20:
        puntuacion_tasa_de_ahorro = 80

    elif tasa_de_ahorro >= 0.15:
        puntuacion_tasa_de_ahorro = 70

    elif tasa_de_ahorro >= 0.10:
        puntuacion_tasa_de_ahorro = 60

    elif tasa_de_ahorro >= 0.05:
        puntuacion_tasa_de_ahorro = 50

    else:
        puntuacion_tasa_de_ahorro = 0

    # ==========================================================
    # Puntuación del indicador:
    # Aprovechamiento del margen financiero
    # ==========================================================

    if aprovechamiento_del_margen_financiero >= 0.90:
        puntuacion_aprovechamiento = 100

    elif aprovechamiento_del_margen_financiero >= 0.75:
        puntuacion_aprovechamiento = 90

    elif aprovechamiento_del_margen_financiero >= 0.60:
        puntuacion_aprovechamiento = 80

    elif aprovechamiento_del_margen_financiero >= 0.45:
        puntuacion_aprovechamiento = 70

    elif aprovechamiento_del_margen_financiero >= 0.30:
        puntuacion_aprovechamiento = 60

    elif aprovechamiento_del_margen_financiero >= 0.15:
        puntuacion_aprovechamiento = 50

    else:
        puntuacion_aprovechamiento = 0

    # ==========================================================
    # Puntuación de la dimensión
    # ==========================================================

    pesos = PESOS_DIMENSIONES["capacidad_de_ahorro"]

    puntuacion_dimension = round(

        (puntuacion_tasa_de_ahorro *
         pesos["tasa_de_ahorro"])

        +

        (puntuacion_aprovechamiento *
         pesos["aprovechamiento_del_margen_financiero"])

    )

    # ==========================================================
    # Estado de la dimensión
    # ==========================================================

    estado = obtener_estado(puntuacion_dimension)

    evaluacion_capacidad_de_ahorro = {

        "puntuacion": puntuacion_dimension,

        "estado": estado

    }

    return evaluacion_capacidad_de_ahorro

evaluacion_capacidad_de_ahorro = (
    evaluar_capacidad_de_ahorro(
        indicadores_financieros
    )
)

print(evaluacion_capacidad_de_ahorro)

{'puntuacion': 70, 'estado': 'En observación'}


In [197]:
def evaluar_endeudamiento(indicadores_financieros):
    """
    Evalúa la dimensión Endeudamiento.

    Parámetros:
        indicadores_financieros (dict): Diccionario con los indicadores
        financieros previamente calculados.

    Retorna:
        dict: Diccionario con la puntuación y estado de la dimensión.
    """

    indicadores = indicadores_financieros["endeudamiento"]

    ratio_de_endeudamiento = (
        indicadores["ratio_de_endeudamiento"]
    )

    presion_de_la_deuda = (
        indicadores["presion_de_la_deuda"]
    )

    costo_promedio_del_endeudamiento = (
        indicadores["costo_promedio_del_endeudamiento"]
    )

    # ==========================================================
    # Puntuación del indicador: Ratio de endeudamiento
    # ==========================================================

    if ratio_de_endeudamiento <= 0.10:
        puntuacion_ratio = 100

    elif ratio_de_endeudamiento <= 0.20:
        puntuacion_ratio = 90

    elif ratio_de_endeudamiento <= 0.30:
        puntuacion_ratio = 80

    elif ratio_de_endeudamiento <= 0.40:
        puntuacion_ratio = 70

    elif ratio_de_endeudamiento <= 0.50:
        puntuacion_ratio = 60

    elif ratio_de_endeudamiento <= 0.60:
        puntuacion_ratio = 50

    else:
        puntuacion_ratio = 0

    # ==========================================================
    # Puntuación del indicador: Presión de la deuda
    # ==========================================================

    if presion_de_la_deuda <= 0.10:
        puntuacion_presion = 100

    elif presion_de_la_deuda <= 0.20:
        puntuacion_presion = 90

    elif presion_de_la_deuda <= 0.30:
        puntuacion_presion = 80

    elif presion_de_la_deuda <= 0.40:
        puntuacion_presion = 70

    elif presion_de_la_deuda <= 0.50:
        puntuacion_presion = 60

    elif presion_de_la_deuda <= 0.60:
        puntuacion_presion = 50

    else:
        puntuacion_presion = 0

    # ==========================================================
    # Puntuación del indicador:
    # Costo promedio del endeudamiento
    # ==========================================================

    if costo_promedio_del_endeudamiento <= 10:
        puntuacion_costo = 100

    elif costo_promedio_del_endeudamiento <= 20:
        puntuacion_costo = 90

    elif costo_promedio_del_endeudamiento <= 35:
        puntuacion_costo = 80

    elif costo_promedio_del_endeudamiento <= 50:
        puntuacion_costo = 70

    elif costo_promedio_del_endeudamiento <= 65:
        puntuacion_costo = 60

    elif costo_promedio_del_endeudamiento <= 80:
        puntuacion_costo = 50

    else:
        puntuacion_costo = 0

    # ==========================================================
    # Puntuación de la dimensión
    # ==========================================================

    pesos = PESOS_DIMENSIONES["endeudamiento"]

    puntuacion_dimension = round(

        (puntuacion_ratio *
         pesos["ratio_de_endeudamiento"])

        +

        (puntuacion_presion *
         pesos["presion_de_la_deuda"])

        +

        (puntuacion_costo *
         pesos["costo_promedio_del_endeudamiento"])

    )

    # ==========================================================
    # Estado de la dimensión
    # ==========================================================

    estado = obtener_estado(puntuacion_dimension)

    evaluacion_endeudamiento = {

        "puntuacion": puntuacion_dimension,

        "estado": estado

    }

    return evaluacion_endeudamiento

evaluacion_endeudamiento = (
    evaluar_endeudamiento(
        indicadores_financieros
    )
)

print(evaluacion_endeudamiento)

{'puntuacion': 68, 'estado': 'En observación'}


In [201]:
def evaluar_comportamiento_de_consumo(
    indicadores_financieros,
    variables_globales
):
    """
    Evalúa la dimensión Comportamiento de Consumo.

    Parámetros:
        indicadores_financieros (dict): Diccionario con los indicadores
        financieros previamente calculados.

        variables_globales (dict): Diccionario con las variables
        globales calculadas previamente.

    Retorna:
        dict: Diccionario con la puntuación y estado de la dimensión.
    """

    consumo_total_por_categoria = (
        variables_globales["consumo_total_por_categoria"]
    )

    # ==========================================================
    # Caso especial:
    # No existen transacciones de consumo
    # ==========================================================

    if consumo_total_por_categoria == 0.0:

        return {

            "puntuacion": 0,

            "estado": obtener_estado(0)

        }

    indicadores = indicadores_financieros["comportamiento_de_consumo"]

    indice_de_concentracion_del_gasto = (
        indicadores["indice_de_concentracion_del_gasto"]
    )

    perfil_de_consumo = indicadores["perfil_de_consumo"]

    predominio_del_gasto = (
        perfil_de_consumo["predominio_del_gasto"]
    )

    diversificacion_del_consumo = (
        perfil_de_consumo["diversificacion_del_consumo"]
    )

    # ==========================================================
    # Puntuación del indicador:
    # Índice de concentración del gasto
    # ==========================================================

    if indice_de_concentracion_del_gasto <= 0.33:

        puntuacion_indice = 100

    elif indice_de_concentracion_del_gasto <= 0.66:

        puntuacion_indice = 70

    else:

        puntuacion_indice = 40

    # ==========================================================
    # Puntuación del indicador:
    # Predominio del gasto
    # ==========================================================

    if predominio_del_gasto == (
        "Predominio en gastos esenciales"
    ):

        puntuacion_predominio = 100

    elif predominio_del_gasto == (
        "Balance entre gastos esenciales y discrecionales"
    ):

        puntuacion_predominio = 80

    else:

        puntuacion_predominio = 50

    # ==========================================================
    # Puntuación del indicador:
    # Diversificación del consumo
    # ==========================================================

    if diversificacion_del_consumo == (
        "Consumo diversificado"
    ):

        puntuacion_diversificacion = 100

    else:

        puntuacion_diversificacion = 50

    # ==========================================================
    # Puntuación de la dimensión
    # ==========================================================

    pesos = PESOS_DIMENSIONES["comportamiento_de_consumo"]

    puntuacion_dimension = round(

        (puntuacion_indice *
         pesos["indice_de_concentracion_del_gasto"])

        +

        (puntuacion_predominio *
         pesos["predominio_del_gasto"])

        +

        (puntuacion_diversificacion *
         pesos["diversificacion_del_consumo"])

    )

    # ==========================================================
    # Estado de la dimensión
    # ==========================================================

    estado = obtener_estado(puntuacion_dimension)

    evaluacion_comportamiento_de_consumo = {

        "puntuacion": puntuacion_dimension,

        "estado": estado

    }

    return evaluacion_comportamiento_de_consumo

evaluacion_comportamiento_de_consumo = (
    evaluar_comportamiento_de_consumo(
        indicadores_financieros,
        variables_globales
    )
)

print(evaluacion_comportamiento_de_consumo)

{'puntuacion': 100, 'estado': 'Saludable'}


In [202]:
def calcular_evaluacion_financiera(
    indicadores_financieros,
    variables_globales
):
    """
    Calcula la evaluación financiera de las cuatro dimensiones.

    Parámetros:
        indicadores_financieros (dict): Diccionario con los indicadores
        financieros previamente calculados.

        variables_globales (dict): Diccionario con las variables
        globales previamente calculadas.

    Retorna:
        dict: Diccionario con la puntuación y estado de cada dimensión.
    """

    evaluacion_balance_financiero = (
        evaluar_balance_financiero(
            indicadores_financieros
        )
    )

    evaluacion_capacidad_de_ahorro = (
        evaluar_capacidad_de_ahorro(
            indicadores_financieros
        )
    )

    evaluacion_endeudamiento = (
        evaluar_endeudamiento(
            indicadores_financieros
        )
    )

    evaluacion_comportamiento_de_consumo = (
        evaluar_comportamiento_de_consumo(
            indicadores_financieros,
            variables_globales
        )
    )

    evaluacion_financiera = {

        "balance_financiero":
            evaluacion_balance_financiero,

        "capacidad_de_ahorro":
            evaluacion_capacidad_de_ahorro,

        "endeudamiento":
            evaluacion_endeudamiento,

        "comportamiento_de_consumo":
            evaluacion_comportamiento_de_consumo

    }

    return evaluacion_financiera

evaluacion_financiera = (
    calcular_evaluacion_financiera(
        indicadores_financieros,
        variables_globales
    )
)

from pprint import pprint

print("Evaluación financiera:\n")

pprint(evaluacion_financiera)

Evaluación financiera:

{'balance_financiero': {'estado': 'Saludable', 'puntuacion': 80},
 'capacidad_de_ahorro': {'estado': 'En observación', 'puntuacion': 70},
 'comportamiento_de_consumo': {'estado': 'Saludable', 'puntuacion': 100},
 'endeudamiento': {'estado': 'En observación', 'puntuacion': 68}}


## Generación de recomendaciones de cada dimensión 

In [203]:
def generar_recomendaciones_balance_financiero(
    indicadores_financieros,
    evaluacion_financiera
):
    """
    Genera las recomendaciones para la dimensión Balance Financiero.

    Parámetros:
        indicadores_financieros (dict): Diccionario con los indicadores
        financieros previamente calculados.

        evaluacion_financiera (dict): Diccionario con la evaluación
        financiera previamente calculada.

    Retorna:
        list: Lista de recomendaciones para la dimensión.
    """

    recomendaciones = []

    indicadores = indicadores_financieros["balance_financiero"]

    balance_mensual = indicadores["balance_mensual"]
    tasa_de_gasto = indicadores["tasa_de_gasto"]
    margen_financiero = indicadores["margen_financiero"]

    estado = (
        evaluacion_financiera["balance_financiero"]["estado"]
    )

    # ==========================================================
    # Recomendación según el Balance mensual
    # ==========================================================

    if balance_mensual > 0:

        recomendaciones.append(
            "Mantener un balance mensual positivo para fortalecer la estabilidad financiera."
        )

    elif balance_mensual == 0:

        recomendaciones.append(
            "Buscar generar un balance mensual positivo incrementando los ingresos o reduciendo los gastos."
        )

    else:

        recomendaciones.append(
            "Recuperar un balance mensual positivo reduciendo gastos o incrementando los ingresos."
        )

    # ==========================================================
    # Recomendación según la Tasa de gasto
    # ==========================================================

    if tasa_de_gasto <= 0.50:

        recomendaciones.append(
            "Mantener el nivel actual de gasto respecto a los ingresos."
        )

    elif tasa_de_gasto <= 0.80:

        recomendaciones.append(
            "Continuar monitoreando el gasto para evitar que aumente."
        )

    elif tasa_de_gasto <= 1.00:

        recomendaciones.append(
            "Reducir gradualmente el porcentaje destinado al gasto mensual."
        )

    else:

        recomendaciones.append(
            "Priorizar la reducción inmediata de gastos o incrementar los ingresos para recuperar el equilibrio financiero."
        )

    # ==========================================================
    # Recomendación según el Margen financiero
    # ==========================================================

    if margen_financiero >= 0.30:

        recomendaciones.append(
            "Mantener el margen financiero actual y destinar parte del excedente al ahorro o inversión."
        )

    elif margen_financiero >= 0.10:

        recomendaciones.append(
            "Buscar incrementar gradualmente el margen financiero mediante una mejor planificación del presupuesto."
        )

    elif margen_financiero >= 0.00:

        recomendaciones.append(
            "Incrementar el margen financiero reduciendo gastos no esenciales o aumentando los ingresos."
        )

    else:

        recomendaciones.append(
            "Recuperar un margen financiero positivo disminuyendo gastos o incrementando los ingresos antes de asumir nuevos compromisos financieros."
        )

    # ==========================================================
    # Recomendación según el Estado de la dimensión
    # ==========================================================

    if estado == "Saludable":

        recomendaciones.append(
            "Mantener las prácticas financieras actuales para conservar el buen desempeño de esta dimensión."
        )

    elif estado == "En observación":

        recomendaciones.append(
            "Dar seguimiento mensual a esta dimensión para evitar que evolucione hacia una situación de riesgo."
        )

    else:

        recomendaciones.append(
            "Priorizar la mejora de esta dimensión antes de asumir nuevos compromisos financieros."
        )

    return recomendaciones

recomendaciones_balance_financiero = (
    generar_recomendaciones_balance_financiero(
        indicadores_financieros,
        evaluacion_financiera
    )
)

from pprint import pprint

print("Recomendaciones - Balance financiero:\n")

pprint(recomendaciones_balance_financiero)

Recomendaciones - Balance financiero:

['Mantener un balance mensual positivo para fortalecer la estabilidad '
 'financiera.',
 'Continuar monitoreando el gasto para evitar que aumente.',
 'Mantener el margen financiero actual y destinar parte del excedente al '
 'ahorro o inversión.',
 'Mantener las prácticas financieras actuales para conservar el buen desempeño '
 'de esta dimensión.']


In [204]:
def generar_recomendaciones_capacidad_de_ahorro(
    indicadores_financieros,
    evaluacion_financiera
):
    """
    Genera las recomendaciones para la dimensión Capacidad de Ahorro.

    Parámetros:
        indicadores_financieros (dict): Diccionario con los indicadores
        financieros previamente calculados.

        evaluacion_financiera (dict): Diccionario con la evaluación
        financiera previamente calculada.

    Retorna:
        list: Lista de recomendaciones para la dimensión.
    """

    recomendaciones = []

    indicadores = indicadores_financieros["capacidad_de_ahorro"]

    tasa_de_ahorro = indicadores["tasa_de_ahorro"]

    aprovechamiento_del_margen_financiero = (
        indicadores["aprovechamiento_del_margen_financiero"]
    )

    estado = (
        evaluacion_financiera["capacidad_de_ahorro"]["estado"]
    )

    # ==========================================================
    # Recomendación según la Tasa de ahorro
    # ==========================================================

    if tasa_de_ahorro >= 0.30:

        recomendaciones.append(
            "Mantener el excelente hábito de destinar una parte importante de los ingresos al ahorro e inversión."
        )

    elif tasa_de_ahorro >= 0.25:

        recomendaciones.append(
            "Continuar fortaleciendo el ahorro para consolidar una mayor estabilidad financiera."
        )

    elif tasa_de_ahorro >= 0.20:

        recomendaciones.append(
            "Mantener el ritmo de ahorro actual y buscar incrementarlo gradualmente."
        )

    elif tasa_de_ahorro >= 0.15:

        recomendaciones.append(
            "Incrementar gradualmente el porcentaje destinado al ahorro."
        )

    elif tasa_de_ahorro >= 0.10:

        recomendaciones.append(
            "Procurar aumentar el ahorro mensual mediante una mejor planificación del presupuesto."
        )

    elif tasa_de_ahorro >= 0.05:

        recomendaciones.append(
            "Priorizar el incremento del ahorro mensual reduciendo gastos no esenciales."
        )

    else:

        recomendaciones.append(
            "Establecer como prioridad aumentar el ahorro mensual para fortalecer la estabilidad financiera."
        )

    # ==========================================================
    # Recomendación según el Aprovechamiento del margen financiero
    # ==========================================================

    if aprovechamiento_del_margen_financiero >= 0.90:

        recomendaciones.append(
            "Mantener el excelente aprovechamiento del margen financiero destinándolo al ahorro o inversión."
        )

    elif aprovechamiento_del_margen_financiero >= 0.75:

        recomendaciones.append(
            "Continuar destinando la mayor parte del margen financiero al ahorro."
        )

    elif aprovechamiento_del_margen_financiero >= 0.60:

        recomendaciones.append(
            "Aprovechar una mayor parte del margen financiero para fortalecer el ahorro."
        )

    elif aprovechamiento_del_margen_financiero >= 0.45:

        recomendaciones.append(
            "Incrementar el porcentaje del margen financiero destinado al ahorro e inversión."
        )

    elif aprovechamiento_del_margen_financiero >= 0.30:

        recomendaciones.append(
            "Reducir gastos discrecionales para aprovechar mejor el margen financiero disponible."
        )

    elif aprovechamiento_del_margen_financiero >= 0.15:

        recomendaciones.append(
            "Destinar una mayor proporción del excedente mensual al ahorro antes de aumentar el consumo."
        )

    else:

        recomendaciones.append(
            "Priorizar el aprovechamiento del margen financiero para construir un fondo de ahorro o inversión."
        )

    # ==========================================================
    # Recomendación según el Estado de la dimensión
    # ==========================================================

    if estado == "Saludable":

        recomendaciones.append(
            "Mantener las estrategias actuales de ahorro para conservar esta fortaleza financiera."
        )

    elif estado == "En observación":

        recomendaciones.append(
            "Dar seguimiento periódico a la capacidad de ahorro para evitar que disminuya con el tiempo."
        )

    else:

        recomendaciones.append(
            "Priorizar el fortalecimiento de la capacidad de ahorro como parte de la planificación financiera personal."
        )

    return recomendaciones

recomendaciones_capacidad_de_ahorro = (
    generar_recomendaciones_capacidad_de_ahorro(
        indicadores_financieros,
        evaluacion_financiera
    )
)

from pprint import pprint

print("Recomendaciones - Capacidad de ahorro:\n")

pprint(recomendaciones_capacidad_de_ahorro)

Recomendaciones - Capacidad de ahorro:

['Incrementar gradualmente el porcentaje destinado al ahorro.',
 'Incrementar el porcentaje del margen financiero destinado al ahorro e '
 'inversión.',
 'Dar seguimiento periódico a la capacidad de ahorro para evitar que disminuya '
 'con el tiempo.']


In [205]:
def generar_recomendaciones_endeudamiento(
    indicadores_financieros,
    evaluacion_financiera
):
    """
    Genera las recomendaciones para la dimensión Endeudamiento.

    Parámetros:
        indicadores_financieros (dict): Diccionario con los indicadores
        financieros previamente calculados.

        evaluacion_financiera (dict): Diccionario con la evaluación
        financiera previamente calculada.

    Retorna:
        list: Lista de recomendaciones para la dimensión.
    """

    recomendaciones = []

    indicadores = indicadores_financieros["endeudamiento"]

    ratio_de_endeudamiento = (
        indicadores["ratio_de_endeudamiento"]
    )

    presion_de_la_deuda = (
        indicadores["presion_de_la_deuda"]
    )

    costo_promedio_del_endeudamiento = (
        indicadores["costo_promedio_del_endeudamiento"]
    )

    estado = (
        evaluacion_financiera["endeudamiento"]["estado"]
    )

    # ==========================================================
    # Recomendación según el Ratio de endeudamiento
    # ==========================================================

    if ratio_de_endeudamiento <= 0.10:

        recomendaciones.append(
            "Mantener el bajo nivel de endeudamiento actual."
        )

    elif ratio_de_endeudamiento <= 0.20:

        recomendaciones.append(
            "Continuar administrando responsablemente las obligaciones financieras."
        )

    elif ratio_de_endeudamiento <= 0.30:

        recomendaciones.append(
            "Vigilar el crecimiento del endeudamiento para mantener una carga financiera saludable."
        )

    elif ratio_de_endeudamiento <= 0.40:

        recomendaciones.append(
            "Reducir gradualmente el porcentaje del ingreso destinado al pago de deudas."
        )

    elif ratio_de_endeudamiento <= 0.50:

        recomendaciones.append(
            "Priorizar la disminución del endeudamiento antes de adquirir nuevas obligaciones financieras."
        )

    elif ratio_de_endeudamiento <= 0.60:

        recomendaciones.append(
            "Elaborar un plan para reducir progresivamente la carga de la deuda."
        )

    else:

        recomendaciones.append(
            "Priorizar la reducción inmediata del endeudamiento para recuperar estabilidad financiera."
        )

    # ==========================================================
    # Recomendación según la Presión de la deuda
    # ==========================================================

    if presion_de_la_deuda <= 0.10:

        recomendaciones.append(
            "Mantener una distribución equilibrada del gasto mensual."
        )

    elif presion_de_la_deuda <= 0.20:

        recomendaciones.append(
            "Continuar controlando el peso de las deudas dentro del presupuesto."
        )

    elif presion_de_la_deuda <= 0.30:

        recomendaciones.append(
            "Vigilar que el pago de deudas no limite otros objetivos financieros."
        )

    elif presion_de_la_deuda <= 0.40:

        recomendaciones.append(
            "Reducir gradualmente la presión de las deudas sobre el presupuesto mensual."
        )

    elif presion_de_la_deuda <= 0.50:

        recomendaciones.append(
            "Reorganizar el presupuesto para disminuir el impacto del pago de deudas."
        )

    elif presion_de_la_deuda <= 0.60:

        recomendaciones.append(
            "Priorizar la disminución de obligaciones financieras para liberar capacidad de gasto."
        )

    else:

        recomendaciones.append(
            "Implementar un plan de reducción de deudas para recuperar flexibilidad financiera."
        )

    # ==========================================================
    # Recomendación según el Costo promedio del endeudamiento
    # ==========================================================

    if costo_promedio_del_endeudamiento == 0:

        recomendaciones.append(
            "Mantener el uso responsable del crédito y evitar adquirir deudas con costos financieros elevados."
        )

    elif costo_promedio_del_endeudamiento <= 10:

        recomendaciones.append(
            "Mantener las condiciones actuales de financiamiento."
        )

    elif costo_promedio_del_endeudamiento <= 20:

        recomendaciones.append(
            "Continuar utilizando fuentes de financiamiento con tasas competitivas."
        )

    elif costo_promedio_del_endeudamiento <= 35:

        recomendaciones.append(
            "Buscar oportunidades para reducir el costo del financiamiento."
        )

    elif costo_promedio_del_endeudamiento <= 50:

        recomendaciones.append(
            "Evaluar alternativas de refinanciamiento con menores tasas de interés."
        )

    elif costo_promedio_del_endeudamiento <= 65:

        recomendaciones.append(
            "Priorizar el pago de las deudas con mayor tasa de interés."
        )

    elif costo_promedio_del_endeudamiento <= 80:

        recomendaciones.append(
            "Reducir el uso de créditos con tasas elevadas y buscar opciones más económicas."
        )

    else:

        recomendaciones.append(
            "Reestructurar o liquidar prioritariamente las deudas con mayor costo financiero."
        )

    # ==========================================================
    # Recomendación según el Estado de la dimensión
    # ==========================================================

    if estado == "Saludable":

        recomendaciones.append(
            "Mantener una administración responsable del endeudamiento para conservar esta fortaleza financiera."
        )

    elif estado == "En observación":

        recomendaciones.append(
            "Dar seguimiento periódico al nivel de endeudamiento para evitar un incremento en el riesgo financiero."
        )

    else:

        recomendaciones.append(
            "Priorizar la reducción del endeudamiento como parte de la estrategia financiera antes de asumir nuevas obligaciones."
        )

    return recomendaciones

recomendaciones_endeudamiento = (
    generar_recomendaciones_endeudamiento(
        indicadores_financieros,
        evaluacion_financiera
    )
)

from pprint import pprint

print("Recomendaciones - Endeudamiento:\n")

pprint(recomendaciones_endeudamiento)

Recomendaciones - Endeudamiento:

['Vigilar el crecimiento del endeudamiento para mantener una carga financiera '
 'saludable.',
 'Reorganizar el presupuesto para disminuir el impacto del pago de deudas.',
 'Priorizar el pago de las deudas con mayor tasa de interés.',
 'Dar seguimiento periódico al nivel de endeudamiento para evitar un '
 'incremento en el riesgo financiero.']


In [206]:
def generar_recomendaciones_comportamiento_de_consumo(
    indicadores_financieros,
    evaluacion_financiera,
    variables_globales
):
    """
    Genera las recomendaciones para la dimensión Comportamiento de Consumo.

    Parámetros:
        indicadores_financieros (dict): Diccionario con los indicadores
        financieros previamente calculados.

        evaluacion_financiera (dict): Diccionario con la evaluación
        financiera previamente calculada.

        variables_globales (dict): Diccionario con las variables
        globales previamente calculadas.

    Retorna:
        list: Lista de recomendaciones para la dimensión.
    """

    consumo_total_por_categoria = (
        variables_globales["consumo_total_por_categoria"]
    )

    # ==========================================================
    # Caso especial:
    # No existen transacciones de consumo
    # ==========================================================

    if consumo_total_por_categoria == 0.0:

        return [

            "Registrar transacciones de consumo de manera consistente para poder evaluar los hábitos financieros."

        ]

    recomendaciones = []

    indicadores = indicadores_financieros["comportamiento_de_consumo"]

    indice_de_concentracion_del_gasto = (
        indicadores["indice_de_concentracion_del_gasto"]
    )

    perfil_de_consumo = indicadores["perfil_de_consumo"]

    predominio_del_gasto = (
        perfil_de_consumo["predominio_del_gasto"]
    )

    diversificacion_del_consumo = (
        perfil_de_consumo["diversificacion_del_consumo"]
    )

    estado = (
        evaluacion_financiera[
            "comportamiento_de_consumo"
        ]["estado"]
    )

    # ==========================================================
    # Recomendación según el Índice de concentración del gasto
    # ==========================================================

    if indice_de_concentracion_del_gasto <= 0.33:

        recomendaciones.append(
            "Mantener una distribución equilibrada del gasto entre las distintas categorías de consumo."
        )

    elif indice_de_concentracion_del_gasto <= 0.66:

        recomendaciones.append(
            "Procurar distribuir el consumo entre más categorías para reducir la dependencia de unos pocos rubros."
        )

    else:

        recomendaciones.append(
            "Revisar la concentración del gasto y buscar una distribución más equilibrada del presupuesto mensual."
        )

    # ==========================================================
    # Recomendación según el Predominio del gasto
    # ==========================================================

    if predominio_del_gasto == (
        "Predominio en gastos esenciales"
    ):

        recomendaciones.append(
            "Mantener la prioridad en los gastos esenciales para fortalecer la estabilidad financiera."
        )

    elif predominio_del_gasto == (
        "Balance entre gastos esenciales y discrecionales"
    ):

        recomendaciones.append(
            "Conservar el equilibrio entre gastos esenciales y discrecionales sin descuidar las necesidades prioritarias."
        )

    else:

        recomendaciones.append(
            "Reducir gradualmente el peso de los gastos discrecionales y priorizar los gastos esenciales."
        )

    # ==========================================================
    # Recomendación según la Diversificación del consumo
    # ==========================================================

    if diversificacion_del_consumo == (
        "Consumo diversificado"
    ):

        recomendaciones.append(
            "Mantener una adecuada diversificación del consumo para reducir la dependencia de una sola categoría."
        )

    else:

        recomendaciones.append(
            "Diversificar gradualmente el consumo para lograr una distribución más equilibrada del presupuesto."
        )

    # ==========================================================
    # Recomendación según el Estado
    # ==========================================================

    if estado == "Saludable":

        recomendaciones.append(
            "Mantener los hábitos actuales de consumo para conservar esta fortaleza financiera."
        )

    elif estado == "En observación":

        recomendaciones.append(
            "Dar seguimiento periódico al comportamiento del consumo para mantener una distribución equilibrada."
        )

    else:

        recomendaciones.append(
            "Priorizar una reorganización del consumo para fortalecer la estabilidad financiera."
        )

    return recomendaciones

recomendaciones_comportamiento_de_consumo = (
    generar_recomendaciones_comportamiento_de_consumo(
        indicadores_financieros,
        evaluacion_financiera,
        variables_globales
    )
)

from pprint import pprint

print("Recomendaciones - Comportamiento de consumo:\n")

pprint(recomendaciones_comportamiento_de_consumo)

Recomendaciones - Comportamiento de consumo:

['Mantener una distribución equilibrada del gasto entre las distintas '
 'categorías de consumo.',
 'Mantener la prioridad en los gastos esenciales para fortalecer la '
 'estabilidad financiera.',
 'Mantener una adecuada diversificación del consumo para reducir la '
 'dependencia de una sola categoría.',
 'Mantener los hábitos actuales de consumo para conservar esta fortaleza '
 'financiera.']


In [207]:
def generar_recomendaciones_financieras(
    indicadores_financieros,
    evaluacion_financiera,
    variables_globales
):
    """
    Genera las recomendaciones financieras para las cuatro dimensiones.

    Parámetros:
        indicadores_financieros (dict): Diccionario con los indicadores
        financieros previamente calculados.

        evaluacion_financiera (dict): Diccionario con la evaluación
        financiera previamente calculada.

        variables_globales (dict): Diccionario con las variables
        globales previamente calculadas.

    Retorna:
        dict: Diccionario con las recomendaciones de cada dimensión.
    """

    recomendaciones_balance_financiero = (
        generar_recomendaciones_balance_financiero(
            indicadores_financieros,
            evaluacion_financiera
        )
    )

    recomendaciones_capacidad_de_ahorro = (
        generar_recomendaciones_capacidad_de_ahorro(
            indicadores_financieros,
            evaluacion_financiera
        )
    )

    recomendaciones_endeudamiento = (
        generar_recomendaciones_endeudamiento(
            indicadores_financieros,
            evaluacion_financiera
        )
    )

    recomendaciones_comportamiento_de_consumo = (
        generar_recomendaciones_comportamiento_de_consumo(
            indicadores_financieros,
            evaluacion_financiera,
            variables_globales
        )
    )

    recomendaciones_financieras = {

        "balance_financiero":
            recomendaciones_balance_financiero,

        "capacidad_de_ahorro":
            recomendaciones_capacidad_de_ahorro,

        "endeudamiento":
            recomendaciones_endeudamiento,

        "comportamiento_de_consumo":
            recomendaciones_comportamiento_de_consumo

    }

    return recomendaciones_financieras

recomendaciones_financieras = (
    generar_recomendaciones_financieras(
        indicadores_financieros,
        evaluacion_financiera,
        variables_globales
    )
)

from pprint import pprint

print("Recomendaciones financieras:\n")

pprint(recomendaciones_financieras)

Recomendaciones financieras:

{'balance_financiero': ['Mantener un balance mensual positivo para fortalecer '
                        'la estabilidad financiera.',
                        'Continuar monitoreando el gasto para evitar que '
                        'aumente.',
                        'Mantener el margen financiero actual y destinar parte '
                        'del excedente al ahorro o inversión.',
                        'Mantener las prácticas financieras actuales para '
                        'conservar el buen desempeño de esta dimensión.'],
 'capacidad_de_ahorro': ['Incrementar gradualmente el porcentaje destinado al '
                         'ahorro.',
                         'Incrementar el porcentaje del margen financiero '
                         'destinado al ahorro e inversión.',
                         'Dar seguimiento periódico a la capacidad de ahorro '
                         'para evitar que disminuya con el tiempo.'],
 'comportamiento_de_consumo

## Generacion de estado y puntuación del perfil financiero general

In [209]:
def calcular_perfil_financiero(evaluacion_financiera):
    """
    Calcula la puntuación y el estado del perfil financiero general.

    Parámetros:
        evaluacion_financiera (dict): Diccionario con la evaluación
        financiera de las cuatro dimensiones.

    Retorna:
        dict: Diccionario con la puntuación y el estado del perfil
        financiero.
    """

    puntuacion_balance = (
        evaluacion_financiera[
            "balance_financiero"
        ]["puntuacion"]
    )

    puntuacion_ahorro = (
        evaluacion_financiera[
            "capacidad_de_ahorro"
        ]["puntuacion"]
    )

    puntuacion_endeudamiento = (
        evaluacion_financiera[
            "endeudamiento"
        ]["puntuacion"]
    )

    puntuacion_consumo = (
        evaluacion_financiera[
            "comportamiento_de_consumo"
        ]["puntuacion"]
    )

    pesos = PESOS_PERFIL_FINANCIERO

    puntuacion = round(

        (puntuacion_balance *
         pesos["balance_financiero"])

        +

        (puntuacion_ahorro *
         pesos["capacidad_de_ahorro"])

        +

        (puntuacion_endeudamiento *
         pesos["endeudamiento"])

        +

        (puntuacion_consumo *
         pesos["comportamiento_de_consumo"])

    )

    estado = obtener_estado(puntuacion)

    perfil_financiero = {

        "puntuacion": puntuacion,

        "estado": estado

    }

    return perfil_financiero

perfil_financiero = (
    calcular_perfil_financiero(
        evaluacion_financiera
    )
)

from pprint import pprint

print("Perfil financiero:\n")

pprint(perfil_financiero)

Perfil financiero:

{'estado': 'En observación', 'puntuacion': 78}


## Generación de recomendacion general del perfil financiero

In [217]:
import os

from google import genai
from dotenv import load_dotenv

# ==========================================================
# Configuración del modelo de lenguaje (Google Gemini)
# ==========================================================

load_dotenv()

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

# Modelo utilizado para generar la recomendación general.
# Si Google publica una nueva versión, basta con actualizar
# esta constante.

MODELO_LLM = "gemini-flash-latest"

cliente = genai.Client(
    api_key=GEMINI_API_KEY
)

In [220]:
def construir_contexto_llm(
    perfil_financiero,
    evaluacion_financiera,
    recomendaciones_financieras
):
    """
    Construye el contexto que será enviado al modelo de lenguaje (LLM)
    para generar el resumen financiero general.

    Parámetros:
        perfil_financiero (dict): Diccionario con la puntuación y el
        estado general del perfil financiero.

        evaluacion_financiera (dict): Diccionario con la evaluación
        financiera de las cuatro dimensiones.

        recomendaciones_financieras (dict): Diccionario con las
        recomendaciones específicas de cada dimensión.

    Retorna:
        str: Contexto estructurado para el LLM.
    """

    contexto = ""

    # ==========================================================
    # Perfil financiero
    # ==========================================================

    contexto += "PERFIL FINANCIERO\n\n"

    contexto += (
        "Resumen general de la evaluación financiera.\n\n"
    )

    contexto += (
        f"Puntuación: "
        f"{perfil_financiero['puntuacion']}\n"
    )

    contexto += (
        f"Estado: "
        f"{perfil_financiero['estado']}\n\n"
    )

    contexto += "-" * 60 + "\n\n"

    # ==========================================================
    # Evaluación financiera
    # ==========================================================

    contexto += "EVALUACIÓN FINANCIERA\n\n"

    for dimension, datos in evaluacion_financiera.items():

        contexto += f"DIMENSIÓN: {dimension}\n"

        contexto += (
            f"Puntuación: "
            f"{datos['puntuacion']}\n"
        )

        contexto += (
            f"Estado: "
            f"{datos['estado']}\n\n"
        )

    contexto += "-" * 60 + "\n\n"

    # ==========================================================
    # Recomendaciones financieras
    # ==========================================================

    contexto += "RECOMENDACIONES ESPECÍFICAS\n\n"

    for dimension, recomendaciones in recomendaciones_financieras.items():

        contexto += f"DIMENSIÓN: {dimension}\n"

        for recomendacion in recomendaciones:

            contexto += (
                f"- {recomendacion}\n"
            )

        contexto += "\n"

    return contexto

contexto_llm = construir_contexto_llm(
    perfil_financiero,
    evaluacion_financiera,
    recomendaciones_financieras
)

print(contexto_llm)

PERFIL FINANCIERO

Resumen general de la evaluación financiera.

Puntuación: 78
Estado: En observación

------------------------------------------------------------

EVALUACIÓN FINANCIERA

DIMENSIÓN: balance_financiero
Puntuación: 80
Estado: Saludable

DIMENSIÓN: capacidad_de_ahorro
Puntuación: 70
Estado: En observación

DIMENSIÓN: endeudamiento
Puntuación: 68
Estado: En observación

DIMENSIÓN: comportamiento_de_consumo
Puntuación: 100
Estado: Saludable

------------------------------------------------------------

RECOMENDACIONES ESPECÍFICAS

DIMENSIÓN: balance_financiero
- Mantener un balance mensual positivo para fortalecer la estabilidad financiera.
- Continuar monitoreando el gasto para evitar que aumente.
- Mantener el margen financiero actual y destinar parte del excedente al ahorro o inversión.
- Mantener las prácticas financieras actuales para conservar el buen desempeño de esta dimensión.

DIMENSIÓN: capacidad_de_ahorro
- Incrementar gradualmente el porcentaje destinado al ah

In [224]:
def generar_recomendacion_general(
    perfil_financiero,
    evaluacion_financiera,
    recomendaciones_financieras
):
    """
    Genera un resumen financiero personalizado utilizando un
    modelo de lenguaje (LLM).

    Parámetros:
        perfil_financiero (dict): Diccionario con la puntuación y
        el estado general del perfil financiero.

        evaluacion_financiera (dict): Diccionario con la evaluación
        financiera de las cuatro dimensiones.

        recomendaciones_financieras (dict): Diccionario con las
        recomendaciones específicas de cada dimensión.

    Retorna:
        str: Resumen financiero personalizado generado por el LLM.
    """

    contexto = construir_contexto_llm(
        perfil_financiero,
        evaluacion_financiera,
        recomendaciones_financieras
    )

    prompt = f"""
Eres un asistente especializado en educación financiera.

Tu tarea es redactar un resumen financiero personalizado para el usuario utilizando exclusivamente la información que se proporciona a continuación.

INSTRUCCIONES

- Utiliza únicamente la información proporcionada.
- No inventes indicadores financieros.
- No inventes recomendaciones nuevas.
- No hagas cálculos adicionales.
- No contradigas la evaluación financiera recibida.
- Resume la situación financiera general del usuario de forma clara y coherente.
- Destaca primero las fortalezas financieras del usuario y después menciona los principales aspectos que puede mejorar.
- Prioriza las dimensiones cuyo estado sea "En riesgo" y posteriormente las que estén "En observación".
- Integra de forma natural las recomendaciones específicas ya generadas por el sistema.
- No reformules ni generalices las recomendaciones; exprésalas manteniendo su significado original.
- No infieras recomendaciones adicionales a partir de los indicadores o puntuaciones.
- Evita repetir literalmente una misma palabra o estructura en oraciones consecutivas cuando puedas expresarla de forma natural sin modificar su significado.
- Mantén un tono profesional, claro, cercano y motivador.
- Finaliza el resumen con un mensaje positivo que motive al usuario a continuar mejorando sus hábitos financieros.
- Evita utilizar lenguaje alarmista o generar preocupación innecesaria.
- No utilices listas ni viñetas.
- Escribe un único párrafo.
- La longitud debe estar aproximadamente entre 80 y 120 palabras.

INFORMACIÓN DISPONIBLE

{contexto}

Genera únicamente el resumen financiero.

No agregues títulos, encabezados ni texto adicional.
"""

    try:

        respuesta = cliente.models.generate_content(

            model=MODELO_LLM,

            contents=prompt

        )

        return respuesta.text.strip()

    except Exception:

        return (
            "No fue posible generar la recomendación general debido "
            "a un problema de conexión con el modelo de lenguaje. "
            "Consulte las recomendaciones específicas de cada dimensión."
        )
    

recomendacion_general = generar_recomendacion_general(
    perfil_financiero,
    evaluacion_financiera,
    recomendaciones_financieras
)

print(recomendacion_general)

Tu evaluación financiera general muestra una puntuación de 78, manteniéndose en estado en observación. Entre tus principales fortalezas se encuentran el comportamiento de consumo y el balance financiero, ambos saludables, por lo que es recomendable mantener las prácticas actuales conservando la prioridad en los gastos esenciales y un balance mensual positivo, destinando parte del excedente al ahorro o inversión. Como aspectos a mejorar dentro de las dimensiones en observación, en capacidad de ahorro debes incrementar gradualmente el porcentaje destinado al ahorro, mientras que en endeudamiento es importante reorganizar el presupuesto para disminuir el impacto del pago de deudas y priorizar aquellas con mayor tasa de interés. ¡Continúa perfeccionando tus hábitos financieros para consolidar tu estabilidad económica!


In [231]:
import copy


def construir_resultado_financiero(
    datos_clasificados,
    perfil_financiero,
    indicadores_financieros,
    evaluacion_financiera,
    recomendaciones_financieras,
    recomendacion_general
):
    """
    Construye el diccionario final con el resultado del análisis
    financiero.

    Parámetros:
        datos_clasificados (dict): Información clasificada del usuario.

        perfil_financiero (dict): Perfil financiero general.

        indicadores_financieros (dict): Indicadores financieros de las
        cuatro dimensiones.

        evaluacion_financiera (dict): Evaluación financiera de las cuatro
        dimensiones.

        recomendaciones_financieras (dict): Recomendaciones específicas
        por dimensión.

        recomendacion_general (str): Resumen financiero generado por el
        modelo de lenguaje.

    Retorna:
        dict: Diccionario final del análisis financiero.
    """

    # ==========================================================
    # Diccionario principal
    # ==========================================================

    resultado_financiero = {

        "usuario": {

            "nombre":
                datos_clasificados["usuario"]["nombre"]

        },

        "perfil_financiero": {

            "puntuacion":
                perfil_financiero["puntuacion"],

            "estado":
                perfil_financiero["estado"]

        },

        "dimensiones": {},

        "recomendacion_general":
            recomendacion_general

    }

    # ==========================================================
    # Construcción automática de las dimensiones
    # ==========================================================

    for dimension in indicadores_financieros:

        # Copia independiente para no modificar el motor financiero
        indicadores = copy.deepcopy(
            indicadores_financieros[dimension]
        )

        # ======================================================
        # Adaptación de categorías únicamente para la API
        # ======================================================

        if dimension == "comportamiento_de_consumo":

            distribucion_api = {}

            for categoria, porcentaje in (
                indicadores[
                    "distribucion_del_gasto_por_categoria"
                ].items()
            ):

                distribucion_api[
                    MAPA_CATEGORIAS_API[categoria]
                ] = porcentaje

            indicadores[
                "distribucion_del_gasto_por_categoria"
            ] = distribucion_api

        # ======================================================
        # Construcción de la dimensión
        # ======================================================

        resultado_financiero["dimensiones"][dimension] = {

            "puntuacion":
                evaluacion_financiera[dimension]["puntuacion"],

            "estado":
                evaluacion_financiera[dimension]["estado"],

            "indicadores":
                indicadores,

            "recomendaciones":
                recomendaciones_financieras[dimension]

        }

    return resultado_financiero

In [232]:
def ejecutar_motor_financiero(datos_clasificados):
    """
    Ejecuta el flujo completo del motor financiero.

    Parámetros:
        datos_clasificados (dict): Información financiera clasificada
        del usuario.

    Retorna:
        dict: Resultado completo del análisis financiero.
    """

    # ==========================================================
    # Variables globales
    # ==========================================================

    variables_globales = calcular_variables_globales(
        datos_clasificados
    )

    # ==========================================================
    # Indicadores financieros
    # ==========================================================

    indicadores_financieros = calcular_indicadores_financieros(
        variables_globales,
        datos_clasificados
    )

    # ==========================================================
    # Evaluación financiera
    # ==========================================================

    evaluacion_financiera = calcular_evaluacion_financiera(
        indicadores_financieros,
        variables_globales
    )

    # ==========================================================
    # Perfil financiero
    # ==========================================================

    perfil_financiero = calcular_perfil_financiero(
        evaluacion_financiera
    )

    # ==========================================================
    # Recomendaciones financieras
    # ==========================================================

    recomendaciones_financieras = generar_recomendaciones_financieras(
        indicadores_financieros,
        evaluacion_financiera,
        variables_globales
    )

    # ==========================================================
    # Recomendación general
    # ==========================================================

    recomendacion_general = generar_recomendacion_general(
        perfil_financiero,
        evaluacion_financiera,
        recomendaciones_financieras
    )

    # ==========================================================
    # Resultado final
    # ==========================================================

    resultado_financiero = construir_resultado_financiero(
        datos_clasificados,
        perfil_financiero,
        indicadores_financieros,
        evaluacion_financiera,
        recomendaciones_financieras,
        recomendacion_general
    )

    return resultado_financiero

In [233]:
resultado_financiero = ejecutar_motor_financiero(
    datos_clasificados
)

import json

print(
    json.dumps(
        resultado_financiero,
        indent=4,
        ensure_ascii=False
    )
)

{
    "usuario": {
        "nombre": "Nicolás Bravo"
    },
    "perfil_financiero": {
        "puntuacion": 78,
        "estado": "En observación"
    },
    "dimensiones": {
        "balance_financiero": {
            "puntuacion": 80,
            "estado": "Saludable",
            "indicadores": {
                "balance_mensual": 10986.0,
                "tasa_de_gasto": 0.6740059347181009,
                "margen_financiero": 0.3259940652818991
            },
            "recomendaciones": [
                "Mantener un balance mensual positivo para fortalecer la estabilidad financiera.",
                "Continuar monitoreando el gasto para evitar que aumente.",
                "Mantener el margen financiero actual y destinar parte del excedente al ahorro o inversión.",
                "Mantener las prácticas financieras actuales para conservar el buen desempeño de esta dimensión."
            ]
        },
        "capacidad_de_ahorro": {
            "puntuacion": 70,
          