spring.application.name=finance-api

# Configuración de Data Source con variables de entorno de Render
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:mem:testdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA / Hibernate para PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true

# Solución Error 500 en Swagger UI /v3/api-docs
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.packages-to-scan=com.team68.finance_api

# Deshabilitar warning de Open In View (mejora rendimiento)
spring.jpa.open-in-view=false

# Opcional: remover warning de dialecto explícito
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect